### ISSUE TITLE
Data types - arrays 번역

### ISSUE THREAD

**Issue by 2kindsofcs** [javascript-tutorial/ko.javascript.info#1]
Data types - arrays 번역 희망합니다.
https://javascript.info/array

**Comment by 2kindsofcs** [comment]
@Violet-Bora-Lee  2kindsofcs@gmail.com 입니다 :)

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 답변이 없으셔서 본 이슈는 다른분께 이관하도록 하겠습니다.

본 이슈는 클로즈 하겠습니다.

**Comment by 2kindsofcs** [comment]
개인적으로 연락을 드렸어서 여기에는 코멘트를 달지 않아도 된다고 생각했었습니다. 히스토리 파악을 위해 남겨두는 게 맞았네요. 챙겨주셔서 감사합니다.
