### ISSUE TITLE
[개선제안] 4.1 객체 파트 3번째 과제 누락

### ISSUE THREAD

**Issue by nimuseel** [javascript-tutorial/ko.javascript.info#1001]
## 자바스크립트 튜토리얼 한국 저장소 개선을 위해 제안할 사항

4.1 객체 파트 3번째 과제 누락
![image](https://user-images.githubusercontent.com/48236404/109419866-031afe00-7a13-11eb-8b7c-667c988dbbbc.png)

## 제안한 이유

TOC에는 과제(5) 로 되어 있는데, 5개의 과제 중 하나가 누락 되어 있습니다.

## 추가적으로 논의할 사항

- 누락된 과제 md 추가 혹은 과제(4)로 수정 후 위 사진의 네모 친 부분 제거
- 제가 작업해도 되는 이슈이면 작업 후 PR 올려도 될까요? 만약 가능하다면 어떻게 수정 반영할지 가이드 해주시면 감사하겠습니다. 🙏

**Comment by Violet-Bora-Lee** [comment]
네 수정 해주시면 좋습니다~
기여는 리드미 파일에 참고할만한 문서를 적어두었는데, 읽어보시고 궁금하거나 이해 안가는 부분있으시면 알려주세요 :)

**Comment by nimuseel** [comment]
> 네 수정 해주시면 좋습니다~
> 기여는 리드미 파일에 참고할만한 문서를 적어두었는데, 읽어보시고 궁금하거나 이해 안가는 부분있으시면 알려주세요 :)

**Comment by nimuseel** [comment]
네 감사합니다! 이따 문제 추가 후 PR 올리겠습니다~

**Comment by nimuseel** [comment]
모르고 close룰 눌러 버렸네요.. ㅠ

**Comment by nimuseel** [comment]
머지 되어 이슈 close 하겠습니다~
