### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by Star-ho** [javascript-tutorial/ko.javascript.info#1002]
## 모던 JavaScript 튜토리얼을 알게 된 경로
Javascript를 시작해보려고 구글링하다가 알게되었습니다

## 컨트리뷰팅 가이드를 1회 이상 정독하셨나요?
네. 정독하였습니다.

## Gmail 아이디
tjdgh1231@donga.ac.kr

**Comment by Violet-Bora-Lee** [comment]
수정 권한 드렸습니다
