### ISSUE TITLE
5-network/01-fetch/article.md 번역 희망

### ISSUE THREAD

**Issue by IMHOJEONG** [javascript-tutorial/ko.javascript.info#103]
JavaScript에 관심이 많은 학생입니다.
의견 남겨보려 왔다가 번역도 해보고 싶어서 요청하게 되었습니다.
제 Gmail 계정은 39ghwjd@gmail.com 입니다.

**Comment by Violet-Bora-Lee** [comment]
권한 드렸습니다 :)
혹시 리뷰 먼저 몇개 해주실수있으실까요? 지금은 번역보단 적체된 리뷰가 많은 상황입니다. 리뷰해보시면서 번역 컨벤션도 확인하시다보면 제가 리뷰 할때 조금 수월하기도 하고요.
