### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by Rohas94** [javascript-tutorial/ko.javascript.info#1033]
## 모던 JavaScript 튜토리얼을 알게 된 경로
구글링을 통해 알았습니다

## 컨트리뷰팅 가이드를 1회 이상 정독하셨나요?
네. 정독하였습니다.

## Gmail 아이디
tjdgh14564@gmail.com

**Comment by Violet-Bora-Lee** [comment]
권한 드렸습니다.
