### ISSUE TITLE
[오번역수정] - 문서 "프라미스 체이닝 중" 문장 중복

### ISSUE THREAD

**Issue by suhwan-cheon** [javascript-tutorial/ko.javascript.info#1047]
## 오번역

![image](https://user-images.githubusercontent.com/52690419/112592841-f8089180-8e49-11eb-8e42-25863962eae3.png)

### [이전]
위 코드는 url에 네트워크 요청을 보내고 프라미스를 반환합니다.
를 실행하면 url에 네트워크 요청이 가고 프라미스가 반환됩니다. 

### [수정]
위 코드를 실행하면 url에 네트워크 요청을 보내고 프라미스를 반환합니다.

## 이슈

불필요한 문장이 중복되어 나타나고 있습니다.

## Pull Request(PR)를 통해 수정할 의향이 있습니까?
네

**Comment by Violet-Bora-Lee** [comment]
이슈 해결되어 종료시키겠습니다.
감사합니다 😄
