### ISSUE TITLE
Missing UI translations. Publishing epub/pdf.

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/ko.javascript.info#1049]
Hi,

Let's publish the Korean version as epub/pdf.

I also found some missing translations in the site UI.

Here are the yml files, please translate them. There are 3 files here.
[modules.zip](https://github.com/javascript-tutorial/ko.javascript.info/files/6215080/modules.zip)

P.S. Translate only what's to the right side from colons `:`, keep the same formatting.

**Comment by Violet-Bora-Lee** [comment]
[modules-ko.zip](https://github.com/javascript-tutorial/ko.javascript.info/files/6226127/modules-ko.zip)

Here is the translated files :)

**Comment by iliakan** [comment]
Thanks! Published!
