### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by SimDaSong** [javascript-tutorial/ko.javascript.info#1063]
## 모던 JavaScript 튜토리얼을 알게 된 경로
JS 공부를 위해 구글링을 하다가 알게 되었습니다.

## 컨트리뷰팅 가이드를 1회 이상 정독하셨나요?
네. 정독하였습니다.

## Gmail 아이디
song98987@korea.ac.kr

**Comment by Violet-Bora-Lee** [comment]
권한 드렸습니다. 감사합니다.
