### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by sa02045** [javascript-tutorial/ko.javascript.info#1065]
## 모던 JavaScript 튜토리얼을 알게 된 경로
유튜버 ZeroCho님이 추천해주셔서 알게됬습니다

## 컨트리뷰팅 가이드를 1회 이상 정독하셨나요?
넵 정독했습니다

## Gmail 아이디
sa02045@gmail.com

**Comment by Violet-Bora-Lee** [comment]
권한 드렸습니다. 감사합니다.
