### ISSUE TITLE
번역 작업 참여하고 싶습니다.

### ISSUE THREAD

**Issue by jjmean2** [javascript-tutorial/ko.javascript.info#108]
안녕하세요. 우연히 OSS 컨트리뷰톤 내용을 보다가 이 프로젝트가 있다는 걸 알게 되었습니다.
안 그래도 요새 자바스크립트를 쓰는 프로젝트를 하고 있어서 공부하면서 번역 작업에도 참여하고 싶습니다. 
jongwan.lee325@gmail.com
입니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 권한부여해드렸습니다.

혹시 리뷰를 먼저 진행 부탁드려도 될까요?
다른분들이 번역 작업하시는건 제가 리뷰를 진행중인데, 제가 번역한 작업물은 아직 리뷰해주시는 분이 없어서요.

오역, 가독성이 떨어지는 문장에 관한 리뷰를 도와주시면, 완성도 있는 튜토리얼을 작성하는데 큰 도움이 될 것 같습니다. 👍

**Comment by jjmean2** [comment]
넵, 알겠습니다. 리뷰는 Pull Request에서 하면 되는 건가요?

**Comment by Violet-Bora-Lee** [comment]
리뷰 원하시는 글 정하시고 대시보드에 이름 적으신다음 수정원하시는 부분 변경하셔서 커밋, pr하시면되요~

**Comment by jjmean2** [comment]
넵. 리뷰도 대시보드에 현황이 있었군요. 알겠습니다~
