### ISSUE TITLE
[오타수정] Part1 6.1 재귀와 스택 과제3 해답

### ISSUE THREAD

**Issue by youngrongoh** [javascript-tutorial/ko.javascript.info#1086]
## 원문

![image](https://user-images.githubusercontent.com/64844815/115980263-50a48900-a5c6-11eb-9941-fcfc6dc29ea9.png)

## 오타수정
"fib(77)을 호출하면 CPU 리소스를 다 잡아먹어서 잠시 엔진이 멈출 수도 **있.**"
-> "fib(77)을 호출하면 CPU 리소스를 다 잡아먹어서 잠시 엔진이 멈출 수도 **있습니다.**"

## 이슈

영어 원문: For instance, fib(77) _may hang up the engine_ for some time eating all CPU resources.

원문과는 의미상 다르지 않으나 번역된 한글 문장이 완결되지 않았습니다.

"멈출 수도 **있.**"에서 "멈출 수도 **있습니다.**"로 수정이 필요합니다.

## Pull Request(PR)를 통해 수정할 의향이 있습니까?
네

**Comment by Violet-Bora-Lee** [comment]
이슈 완료되어 종료시키겠습니다.
감사합니다 👍
