### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by DoGooRi** [javascript-tutorial/ko.javascript.info#1088]
## 모던 JavaScript 튜토리얼을 알게 된 경로
자바스크립트 관련된 오픈소스에 기여를 해보고 싶어서 검색하다가 모던 JavaScript 튜토리얼를 알게되었고
한국어 번역 기여를 할 수 있다고 알게되어 레포를 찾게되었습니다.

## 컨트리뷰팅 가이드와 링크 걸린 문서를 1회 이상 정독하셨나요?
네 정독했습니다.

## Gmail 아이디
gudjsgh6@gmail.com

**Comment by Violet-Bora-Lee** [comment]
권한 드렸습니다. 감사합니다.
