### ISSUE TITLE
[과제 번역] focus와 blur 과제, Edit TD on click 문제 번역

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#1092]
### 작업할 내용

focus와 blur 과제, Edit TD on click 문제 번역
https://ko.javascript.info/focus-blur#ref-3145

담당자: @belol311

**Comment by belol311** [comment]
이슈 종료되었습니다.

**Comment by Violet-Bora-Lee** [comment]
@belol311  기여해 주셔서 감사합니다.
