### ISSUE TITLE
[과제 번역] focus와 blur 과제, Keyboard-driven mouse 문제 번역

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#1095]
### 작업할 내용

focus와 blur 과제, Keyboard-driven mouse 문제 번역
https://ko.javascript.info/focus-blur#ref-3146

담당자: @gusgotoyu365

**Comment by gusgotoyu365** [comment]
이슈 close 해주세요

**Comment by Violet-Bora-Lee** [comment]
@gusgotoyu365  기여해 주셔서 감사합니다.
