### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by bigsaigon333** [javascript-tutorial/ko.javascript.info#1107]
## 모던 JavaScript 튜토리얼을 알게 된 경로
React 공식홈페이지에서 추천하는 JS 레퍼런스로 알게 되었습니다.

## 컨트리뷰팅 가이드와 링크 걸린 문서를 1회 이상 정독하셨나요?
 네. 정독하였습니다.

## Gmail 아이디
likepeppermint@gmail.com 

안녕하세요~ 대시보드 수정 권한 요청드립니다~! 앞으로 잘 부탁드립니다 :smile:

**Comment by Violet-Bora-Lee** [comment]
권한드렸습니다. 감사합니다.
