### ISSUE TITLE
[내용 수정]자바스크립트기본-자료형 호환성이슈 부분

### ISSUE THREAD

**Issue by narongchan** [javascript-tutorial/ko.javascript.info#1109]
현재 사파리버전 14.0.3에서도 bigint형 사용이 가능해서 호환성문제에서 사파리도 지원하는것으로 수정해주시면 좋을것 같습니다

<img width="817" alt="image" src="https://user-images.githubusercontent.com/63002393/118365456-d6b95b80-b5d7-11eb-9f83-6edbb1631289.png">

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 영어 저장소에도 해당 내용을 제보해주시는건 어떨지 건의드려봅니다.
5월말까지 기다려보았다가, 이슈 생성이 안되었다면 제가 이슈 만들어보도록 하겠습니다. 😄

**Comment by narongchan** [comment]
아, 네! 영어 저장소에도 제보하겠습니다:) 감사합니다😃

**Comment by narongchan** [comment]
![image](https://user-images.githubusercontent.com/63002393/118942071-5a36cc00-b98d-11eb-928c-88f1da9300a0.png)
영어판인 https://javascript.info/types 에는 safari에서 bigint를 지원하는 것으로 나와있더라구요!:)
혹시 그래도 제보해야할까요??! 제보해야한다면 제가 하겠습니다:)😉

**Comment by Violet-Bora-Lee** [comment]
아하 이미 원문은 업데이트 되었군요! 그럼 Pull Request 만들어주시던가 아님 제가 작업하겠습니다 😀

**Comment by Violet-Bora-Lee** [comment]
이슈 해결되어 종료합니다.
