### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by tco0427** [javascript-tutorial/ko.javascript.info#1110]
## 모던 JavaScript 튜토리얼을 알게 된 경로
CodeTriage페이지를 통해서 알게되었습니다!

## 컨트리뷰팅 가이드와 링크 걸린 문서를 1회 이상 정독하셨나요?
네. 정독하였습니다.

## Gmail 아이디
a29661498@gmail.com

**Comment by Violet-Bora-Lee** [comment]
권한 드렸습니다. 감사합니다.
