### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by mass2527** [javascript-tutorial/ko.javascript.info#1113]
## 모던 JavaScript 튜토리얼을 알게 된 경로
github를 통해 알게 되었습니다.

## 컨트리뷰팅 가이드와 링크 걸린 문서를 1회 이상 정독하셨나요?
네. 정독하였습니다.

## Gmail 아이디
dongre2527@gmail.com

## 주의 사항
권한을 드렸지만, 문서 수정이 안 된다고 문의하시는 분들이 있으십니다. 권한 추가가 되었다는 메일이 왔으면 정상적으로 수정 권한이 주어진 것으로 생각하시면 됩니다.

권한 관련 메일을 받으셨지만, 수정이 안 된다면 로그인되어있는 계정이 본 이슈에 적어주신 계정과 일치한 지 확인 부탁드립니다. 특히 gmail 계정을 여러 개 사용중이시라면 주의 부탁드립니다.

**Comment by Violet-Bora-Lee** [comment]
권한 드렸습니다. 감사합니다.
