### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by proceane** [javascript-tutorial/ko.javascript.info#1125]
## 모던 JavaScript 튜토리얼을 알게 된 경로
ex) 오픈소스에 기여하고싶어서 여러 오픈소스들을 찾다가 해당 프로젝트를 알게되었습니다.

## 컨트리뷰팅 가이드와 링크 걸린 문서를 1회 이상 정독하셨나요?
ex) 네. 정독하였습니다.

## Gmail 아이디
proceane1@gmail.com

## 주의 사항
권한을 드렸지만, 문서 수정이 안 된다고 문의하시는 분들이 있으십니다. 권한 추가가 되었다는 메일이 왔으면 정상적으로 수정 권한이 주어진 것으로 생각하시면 됩니다.

권한 관련 메일을 받으셨지만, 수정이 안 된다면 로그인되어있는 계정이 본 이슈에 적어주신 계정과 일치한 지 확인 부탁드립니다. 특히 gmail 계정을 여러 개 사용중이시라면 주의 부탁드립니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 이슈 대응이 너무 늦었습니다.
권한 드렸습니다. 기다려 주셔서 감사합니다 👍
