### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by beomjookim** [javascript-tutorial/ko.javascript.info#1197]
## 모던 JavaScript 튜토리얼을 알게 된 경로
블로그에서 알게 되었습니다.

## 컨트리뷰팅 가이드와 링크 걸린 문서를 1회 이상 정독하셨나요?
네

## Gmail 아이디
globalman96@likelion.org

## 비고
미국에서 대학을 다니고 있습니다. 활발한 활동을 하겠습니다!

**Comment by Violet-Bora-Lee** [comment]
권한 추가드렸습니다. 기다려주셔서 감사합니다.
