### ISSUE TITLE
[오타수정] 나머지 매개변수와 스프레드 문법

### ISSUE THREAD

**Issue by jin0106** [javascript-tutorial/ko.javascript.info#1213]
## 원문

![image](https://user-images.githubusercontent.com/53500163/147357960-8890972e-b44c-4e85-ad6e-d044d25782fd.png)
 

## 오타수정
주석 부분을 SoftWare Engineer, Researcher로 바꿔야합니다

## 이슈

   titles = ["Software Engineer", "Researcher"] 이렇게 저장이 되므로 titles[0]은 Software Engineer, titles[1]은 Researcher가 되야 합니다

## Pull Request(PR)를 통해 수정할 의향이 있습니까?
네

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 수정,배포되어 이슈 닫도록 하겠습니다.
