### ISSUE TITLE
[오타수정] Part 3 4.2 localStorage와 sessionStorage 문자열만 사용

### ISSUE THREAD

**Issue by inhyuck** [javascript-tutorial/ko.javascript.info#1400]
## 원문
https://ko.javascript.info/localstorage#ref-1524
<img width="819" alt="스크린샷 2022-04-30 오전 11 47 39" src="https://user-images.githubusercontent.com/25454596/166087659-fb0b0dd5-5120-4a42-988b-64275d642220.png">

## 오타수정
예시에 파란색으로 표시된 sessionStorage가 localStorage 로 변경되어야합니다.

## 이슈
localStorage와 sessionStorage 파트에서는 localStorage와 sessionStorage 에 대한 개요를 먼저 설명하고 localStorage -> sessionStorage 순서로 설명하고 있습니다. 이미지에 표시한 부분은 아직 sessionStorage 영역이 소개되기 전 부분으로 다른 예시와 마찬가지로 localStorage 로 예제를 설명하는게 적절합니다.

https://javascript.info/localstorage#strings-only 원문에도 localStorage 로 설명되어 있습니다.

## Pull Request(PR)를 통해 수정할 의향이 있습니까?
네

**Comment by Violet-Bora-Lee** [comment]
영어 원문이 12개월전에 수정되었는데, 영어 저장소꺼 땡겨온지가 좀 오래되어서 반영이 안되어있네요.
https://github.com/javascript-tutorial/en.javascript.info/commit/237920b71ea72a5ca308c626fc5e4ad1e2db43fb

찾아주셔서 너무 감사드립니다.

바로 머지진행할게요
