### ISSUE TITLE
[개선제안] nullish 연산자 문서의 개선이 필요합니다.

### ISSUE THREAD

**Issue by koremp** [javascript-tutorial/ko.javascript.info#1412]
## 자바스크립트 튜토리얼 한국 저장소 개선을 위해 제안할 사항

현재 [한국어 nullish 연산자 문서](https://ko.javascript.info/nullish-coalescing-operator)는 [영어 nullish 연산자 문서]( https://javascript.info/nullish-coalescing-operator)와 동일하게 번역되어있는데요, nullish 연산자가 `null`, `undefined`만 주로 다루고 `NaN`은 아예 다루지 않고 있습니다. 이 점에 대한 보완이 필요할 것 같은데, 제가 현재 자바스크립트를 다시 공부하는 중이여서 혹여나 제가 잘못 이해한 것일수도 있겠습니다만, 이 경우에는 원문의 레포지토리에 이슈를 남기거나 PR을 제안해야할 것 같아요. 

## 제안한 이유

위와 동일

## 추가적으로 논의할 사항

원문 문서의 번역 뿐만 아니라, 이 이슈와 같이 원문에도 추가해야할 정보들이 있을 경우 어떻게 할 것인지에 대해 논의된 사항이 있을까요?

**Comment by koremp** [comment]
또한 (화살표 함수 기본)[https://ko.javascript.info/arrow-functions-basics]에서 

```
아직 끝나지 않았습니다.
지금까진 간결함이라는 특징을 중심으로 화살표 함수에 대해 알아보았습니다. 하지만 이게 다가 아닙니다!

화살표 함수는 여기서 소개한 기능 이외에도 다른 흥미로운 기능을 지원합니다.

자세한 내용을 배우려면 자바스크립트의 다른 내용들을 더 알아야 합니다. 화살표 함수의 깊은 내용을 알기위해 필요한 내용을 배운 후에 [화살표 함수 다시 살펴보기](https://ko.javascript.info/arrow-functions)에서 그 내용들을 다루도록 하겠습니다.

지금까진 본문이 한 줄인 화살표 함수, 화살표 함수가 콜백으로 쓰인 경우에 대해서 알아보았습니다.
```

라고 설명되어있는데, 이 문서에서 `화살표 함수가 콜백으로 쓰인 경우`에 대해 설명, 서술해놓은 것이 없기 때문에, 문서 자체에 오류가 있어보입니다.

**Comment by Violet-Bora-Lee** [comment]
화살표 함수 관련해선 별도의 이슈를 만들어주세요.

**Comment by Violet-Bora-Lee** [comment]
nullish 병합연산자에서 NaN을 다뤄야 하는 이유를 알수있을까요?
명세서에도 언급되어있지 않는데 다뤄야 할 이유를 알고계시다면 공유부탁드립니다.

**Comment by koremp** [comment]
제가 잘못 이해한 것이었네요. 
![image](https://user-images.githubusercontent.com/18482476/166336419-42b130dd-df23-4e8d-bcca-f2ef016eddc7.png)

어제 PR 올리기 전에 콘솔에서 확인했었던 것 같은데, 결과를 잘못 인식했던 것 같아요. 제가 오해하여 컨트리뷰터님의 시간을 빼앗은 것 같아 죄송합니다. 앞으로는 좀 더 검토하고, 이슈를 올리도록 할게요.
