### ISSUE TITLE
대시보드 권한요청

### ISSUE THREAD

**Issue by patiencendiligence** [javascript-tutorial/ko.javascript.info#147]
안녕하세요, 우연히 흘러들어왔습니다. 번역참여 희망합니다. 
patiencendiligence@gmail.com

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 권한드렸습니다.
리뷰를 몇건 먼저 진행하시고 번역해주셨으면 합니다.
저희 컨벤션 관련 리드미와 시트, 위키를 꼭 읽어주세요.
많은시간을 투자해서 번역을 하셔도 제대로 번역이 되지 않으면 문서 전체의 퀄리티를 위해 PR을 받지 않고있습니다.

리뷰에 참여하셔서 오타나 가독성이 떨어지는 문장 수정 후 PR날리시는것부터 하시면 좋을것 같아요 👍

**Comment by patiencendiligence** [comment]
감사합니다 !👍👍
