### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by HandsomeChoco** [javascript-tutorial/ko.javascript.info#1562]
## 모던 JavaScript 튜토리얼을 알게 된 경로
토이프로젝트에 필요한 내용 검색을 통해서.

## 컨트리뷰팅 가이드와 링크 걸린 문서를 1회 이상 정독하셨나요?
네, 정독하였습니다.

## Gmail 아이디
kkb931115@gmail.com

## 주의 사항
확인하였습니다.

**Comment by Violet-Bora-Lee** [comment]
권한 드렸습니다. 참여해주셔서 감사합니다.
