### ISSUE TITLE
i want to get a dashboard permission !

### ISSUE THREAD

**Issue by kimkyungbae** [javascript-tutorial/ko.javascript.info#157]
자바스크립트 한글화에 기여하고싶습니다. !

m42977789@gmail.com

**Comment by Violet-Bora-Lee** [comment]
권한드렸습니다.
리뷰 먼저 많이 해보시고, 저희 스타일 익히신다음에 번역 기여해주시면 좋을 것 같습니다.
위키와 리드미를 꼼꼼히 확인해주세요 👍

**Comment by kimkyungbae** [comment]
알겠습니다 !
-----Original Message-----
