### ISSUE TITLE
1-js/06-advanced-functions/ 번역 희망

### ISSUE THREAD

**Issue by singularity-code** [javascript-tutorial/ko.javascript.info#16]
안녕하세요. 번역작업 함께하고 싶습니다. 
javascript-tutorial-ko/1-js/06-advanced-functions/01-recursion 부터 시작하겠습니다.
neoxrock@gmail.com 입니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 권한 추가해드렸습니다.
반갑습니다 👍

**Comment by singularity-code** [comment]
확인했습니다 👍
