### ISSUE TITLE
[Bug report] 웹사이트 접속 불가

### ISSUE THREAD

**Issue by moonsung1234** [javascript-tutorial/ko.javascript.info#1710]
## 🐛 Bug report
제목 그대로 웹사이트 접속이 불가한 상태인 것 같습니다.(관련 페이지 모두)

## 환경
윈도우 10, 갤럭시 A34 안드로이드 13 (웹사이트여서 의미는 크게 없지만)

**Comment by Violet-Bora-Lee** [comment]
안녕하세요, 현재 접속 가능해서 이슈는 일단 닫아놓겠습니다.

이슈 올려주셔서 감사합니다.
