### ISSUE TITLE
[신규 번역] 숫자형 과제 번역

### ISSUE THREAD

**Issue by cocoa-salon** [javascript-tutorial/ko.javascript.info#1717]
### 작업할 내용
8-random-min-max 과제 해설(solution.md) 파일 내 5번 라인 번역
https://ko.javascript.info/number
<img width="855" alt="image" src="https://github.com/javascript-tutorial/ko.javascript.info/assets/38235501/942f97d0-955b-4b50-988f-8ead3d54fe3a">

**Comment by Violet-Bora-Lee** [comment]
작업이 완료되어 이슈 종료합니다.
다음부턴 스스로 닫아주세요.
