### ISSUE TITLE
1-js/02-first-steps/13-switch/article.md 번역 희망

### ISSUE THREAD

**Issue by devhaeyeon** [javascript-tutorial/ko.javascript.info#19]
안녕하세요. 번역작업 함께하고 싶습니다.
 1-js/02-first-steps/13-switch/article.md 부터 시작하겠습니다.
devhaeyeon@gmail.com 입니다.

**Comment by Violet-Bora-Lee** [comment]
환영합니다 👍 
시트 권한을 추가해드렸어요. In progress로 해당 문서 상태를 변경하시고 번역에 참여해 주시면 됩니다 :)
Translator이름을 꼭 적어주세요~
