### ISSUE TITLE
6-data-storage/02-localstorage/article.md 번역

### ISSUE THREAD

**Issue by sojeongw** [javascript-tutorial/ko.javascript.info#211]
LocalStorage, SessionStorage 번역 진행하겠습니다. 구글 Task Manager 시트에도 기록해두었습니다.

**Comment by sojeongw** [comment]
[](url)

**Comment by Violet-Bora-Lee** [comment]
번역 완료되어 이슈 닫겠습니다.
https://ko.javascript.info/localstorage
기여해 주셔서 감사합니다 👍 👍
