### ISSUE TITLE
대시보드 권한 요청합니다 1-js/08-Prototypes, inheritance/03 Native prototypes 번역 희망

### ISSUE THREAD

**Issue by koDaegon** [javascript-tutorial/ko.javascript.info#214]
1-js/08-prototypes/03-native-prototypes/article.md
대시보드 권한 요청드립니다.
> Gmail : ko.daegonkim@gmail.com

**Comment by koDaegon** [comment]
1-js/08-prototypes/03-native-prototypes/article.md

**Comment by Violet-Bora-Lee** [comment]
권한드렸습니다.
리뷰 위주로 참여하시면서 문체와 번역 스타일 공부 하신 후 번역 참여 부탁드립니다.
위키와 리드미, 공유드린 스프레드시트의 각 시트에 있는 내용들을 꼼꼼하게 읽어주세요.
