### ISSUE TITLE
falsy의 번역에 대하여

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#230]
현재는 용어집에 falsy를 거짓 같은 값으로 번역하기로 하였는데,
해당 개념이 최초로 나오는 article에서 최초 등장시에만 **falsy(거짓 같은 값)**으로 영-한 병기해주고, 나머지 글에서는 번역하지 않는것으로 진행하려 합니다.

truthy도 마찬가지.

**Comment by sojeongw** [comment]
제가 하겠습니다.

**Comment by Violet-Bora-Lee** [comment]
용어집 업데이트 완료하였고, 번역도 컨벤션 대로 진행되고 있어서 이슈 종결합니다.
