### ISSUE TITLE
배열 과제 번역

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#235]
배열에 해당하는 과제가 번역이 안되어 있습니다.
배열을 학습한 이후 과제 번역에 기여해주세요 🥇

**Comment by SimEunJu** [comment]
이슈에 참여하고 싶으면 대시보드 변경하고 번역 진행하면 되는 건가요? :smiley:

**Comment by Violet-Bora-Lee** [comment]
넵 :) 진행하시게되면 여기에도 기록 남겨주세요(중복작업방지용)

**Comment by SimEunJu** [comment]
넵넵! 진행하도록 하겠습니다 :smiley_cat:

**Comment by Violet-Bora-Lee** [comment]
https://github.com/javascript-tutorial/ko.javascript.info/commit/220ddc7c40ce76b30b3ca4a62d92bd034715cafe

번역 완료되어 본 이슈도 종료하겠습니다.
