### ISSUE TITLE
맵과 셋 과제 번역

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#236]
맵과 셋에 해당하는 과제가 번역이 안되어 있습니다.
맵과 셋을 학습한 이후 과제 번역에 기여해주세요 🥇

**Comment by JuYeong0413** [comment]
제가 진행하겠습니다. 😃

**Comment by JuYeong0413** [comment]
맵과 셋 과제 번역 및 머지 완료되어 이슈 클로징 요청드립니다. 😃 #257

**Comment by Violet-Bora-Lee** [comment]
넵 이슈 닫겠습니다.
감사합니다 😃😃😃😃
