### ISSUE TITLE
프로토타입 상속 과제 번역

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#246]
프로토타입 상속의 과제가 번역이 안되어 있습니다.
프로토타입 상속을 학습한 이후 과제 번역에 기여해주세요 🥇

**Comment by Junkim93** [comment]
제가 진행하겠습니다 :)

**Comment by Violet-Bora-Lee** [comment]
번역 완료로 이슈 종료합니다.

https://ko.javascript.info/prototype-inheritance
