### ISSUE TITLE
문자열번역을 도와주실 자바스크립트 고수의 도움이 필요합니다!

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#247]
특수 문자 `\xXX`, `\uXXXX`, `\u{X…XXXXXX}`에 관한 설명과
[내부 유니코드](http://javascript.info/string#internals-unicode) 관련 번역을 도와주실 자바스크립트 고수의 도움이 필요합니다.

**Comment by Violet-Bora-Lee** [comment]
- 원문: http://javascript.info/string
- 미완성 번역문: https://github.com/javascript-tutorial/ko.javascript.info/blob/master/1-js/05-data-types/03-string/article.md

거의 다 되었는데, 특수문자쪽은 제가 완벽히 이해하지 못하고 번역하고있다고 생각되어 다시 원문으로 바꾼 상태입니다.

**Comment by sangwoo108** [comment]
짧은 지식을 공유드리자면,
utf16은 16bit(2byte)를 기본 단위로 사용하는 인코딩입니다. 그러나 이 경우에 모든 유니코드를 16bit(2byte)만으로는 표현할수 없기 때문에, 이 범위를 넘어서는 문자는 한단위를 덧붙여 총 4byte를 가지고 표현을 하게 됩니다. 이를 써로게이트 페어라고 부릅니다.

16bit안에 들어가는 것들은 유니코드상에서 BMP라고 부르는 기본 평면으로, 한중일 문자를 포함하고 있습니다. 원문의 상형문자가 포함된다는 것은 이를 의미하는듯 합니다.

또 몇몇 메서드의 경우 'surrogate pair를 aware하지 못한다'는 언급이 있는데, 이는 surrogate pair임을 동적으로 인지하여, 두 단위(32bit)을 묶어서 파싱을 해야하는데 그렇지 못하고 각각을 하나의 캐릭터로 파싱한다는 의미입니다.

위의 \xXX \uXXXX 의 경우에는 각각 8bit / 16bit이 고정된 리터럴으로 보입니다.
console.log('\x7a')      // z, 8bit 고정이므로 ascii 번위를 넘어서는 문자 리터럴 표현 불가
console.log('\u007a')  // z, 16bit 고정이므로 BMP를 넘어서는 문자 리터럴 표현 불가
console.log('\u7z') // error

한편 \u{x..} 가변 bit을 줄수 있고 최대 32bit까지 가능합니다
console.log('\u{7a}')  // z

**Comment by Violet-Bora-Lee** [comment]
번역진행중입니다.

**Comment by Violet-Bora-Lee** [comment]
@sangwoo108 
달아주신 코멘트 참고하여 번역 마쳤습니다. 감사합니다 :) 이슈 종료하겠습니다.
