### ISSUE TITLE
원문엔 없으나, 자연스러운 글의 흐름이나 독자의 이해를 돕기위해 삽입한 부가설명에 대한 의견

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#265]
번역 업계 구루이신 선생님이 번역할 땐 `있는 것 빼지 말고, 없는 것 더하지 말아야 한다`라는 원칙을 지켜야 한다고 말씀해주셨습니다.

그런데 `누구나 이해하기 쉬운 튜토리얼`을 만들려고 하다 보니 저도 번역하면서 군더더기를 조금씩 넣게 되더라고요. 부차적인 설명은 최대한 줄여야 하는데 말이죠.

소수 인원과 프로젝트 진행할 땐 이 문제점을 발견하지 못하였는데, 리뷰에 참여해주시는 분들이 많아지면서 제가 저질렀던 실수(?)들이 속속들이 드러나고 있네요.

이 부분에 대하여 컨트리뷰터분들의 의견이 궁금하여 이슈 남겨봅니다.

지금까진 오역이 있지 않으면 그냥 두는 게 나을 것 같다고 코멘트 남기곤 했는데, 다양한 의견을 듣고자 합니다.

**Comment by JuYeong0413** [comment]
개인적으로는 튜토리얼의 특성상 부가설명이 추가되는 것에는 긍정적으로 생각합니다. 😃 다만 설명이 너무 구구절절 길어지거나, 원문의 의미를 왜곡시키지는 않는 선에서 이루어져야 할 것 같아요. 어느정도의 부가설명이 괜찮은지 객관적인 기준을 정하는 건 어려워 보이는데... 컨트리뷰터분들이 는 튜토리얼의 특성상 부가설명이 추가되는 것에는 긍정적으로 생각합니다. 😃 다만 설명이 너무 구구절절 길어지거나, 원문의 의미를 왜곡시키지는 않는 선에서 이루어져야 할 것 같아요. 어느정도의 부가설명이 괜찮은지 객관적인 기준을 정하는 건 어려워 보이는데... 컨트리뷰터분들이 본인이 진행하고 있는 리뷰나 번역 외에도 다른 분들이 하신 작업을 많이 봐주시고 의견을 내 주신다면 더 나은 글이 되지 않을까 싶습니다!

**Comment by sangwoo108** [comment]
'역주'를 추가로 다는 방법이 있을것 같습니다. 

그러나 원문과 번역문이 줄단위로 1:1 매칭되어야하는 구조라 조금 어려움이 있을듯한데요, 역주를 모아놓은 note.md 등을 추가로 만들고 링크를 원문에 붙여볼 수 있을것 같습니다.

e.g.
'a는 b 입니다([역주1](ko.javascript.info/note.md#foo)).'

**Comment by Violet-Bora-Lee** [comment]
#239 discussion

**Comment by Violet-Bora-Lee** [comment]
번역자가 부가설명을 추가할 경우 (설명설명설명설명설명 - `옮긴이`)를 붙이도록 컨벤션에 추가하도록 하겠습니다.

참고: 역주 등의 표현은 옛날 느낌이어서 요즘 출판업계에선 `옮긴이`라고 표현한다고 하네요.

**Comment by Violet-Bora-Lee** [comment]
리드미 파일을 업데이트 하였으므로, 이슈 종료합니다.
