### ISSUE TITLE
번역작업 희망

### ISSUE THREAD

**Issue by SeonHyungJo** [javascript-tutorial/ko.javascript.info#27]
안녕하세요. 번역작업 함께하고 싶습니다.
seonhyung.jo@gmail.com 입니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 편집권한 드렸습니다.
반갑습니다 :)

**Comment by Violet-Bora-Lee** [comment]
저희 오픈카톡방도 있으니, 소통 원하시면 들어와주세요~
https://open.kakao.com/o/gSBnoLab

**Comment by SeonHyungJo** [comment]
네 고맙습니다~
