### ISSUE TITLE
1-js/11-async/01-callbacks/article.md 어색한 문장

### ISSUE THREAD

**Issue by sojeongw** [javascript-tutorial/ko.javascript.info#284]
**원문**
The function is called “asynchronously,” because the action (script loading) finishes not now, but later.

**번역문**
함수 호출은 "비동기적으로" 이뤄집니다. 스크립트를 읽는 데 시간이 걸리기 때문에, 함수에서 수행하려는 동작이 지금이 아니라 나중에 종료되기 때문입니다.

**issue**
번역문에 `때문에`가 두 번 들어가서 가독성이 떨어집니다. 더 나은 문장을 고민하고 있습니다.

**Comment by Violet-Bora-Lee** [comment]
df8b3fd0036a41efa2e4f869796cddd357462fe4

**Comment by sojeongw** [comment]
고생 많으셨습니다! 이 이슈는 close 하겠습니다~
