### ISSUE TITLE
6-data-storage/02-localstorage/article.md에서 origin 번역

### ISSUE THREAD

**Issue by sojeongw** [javascript-tutorial/ko.javascript.info#317]
#279 

`origin` 번역을 고민하고 있습니다. `원본`이나 `출처`는 딱 들어맞지 않는 것 같아서요. 적합한 단어가 생각나시면 의견 부탁드립니다.

**Comment by Violet-Bora-Lee** [comment]
기존에 작업해주신 `오리진`이 좋을것같아요
