### ISSUE TITLE
4-binary/02-text-decoder/article.md 본문 번역 진행

### ISSUE THREAD

**Issue by kimkyungbae** [javascript-tutorial/ko.javascript.info#334]
이슈 제목:4-binary/02-text-decoder/article.md 번역 진행 하고자합니다.

번역을 진행하려하는데 저번에 권한을 부여 받았는데 구글 시트 수정이 불가합니다 ㅠ

m42977789@gmail.com 권한 한번 더 확인 부탁드립니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 권한 드렸습니다.
제가 누락한것같아요.

REAEME꼼꼼히 일어보시고 번역 부탁드릴게요.
감사합니다.
