### ISSUE TITLE
1-js/04-object-basics/01-object/article.md 어색한 문장

### ISSUE THREAD

**Issue by SE0T00L** [javascript-tutorial/ko.javascript.info#353]
**원문**
Square brackets also provide a way to obtain the property name as the result of any expression – as opposed to a literal string – like from a variable as follows:

**번역문**
대괄호 표기법을 사용하면 문자열뿐만 아니라 모든 표현식의 평가 결과를 프로퍼티 키로 사용할 수 있습니다. 아래 예시에선 변수를 키로 사용하고 있습니다.

**issue**
이 문장을 어떻게 수정하면 좋을지 고민하고 있습니다.

**Comment by IMHOJEONG** [comment]
키 대신 이름을 써야 맞는 거 같은데요

**Comment by Violet-Bora-Lee** [comment]
프로퍼티 키는 프로퍼티 이름이라고도 불립니다.

참고: https://github.com/javascript-tutorial/ko.javascript.info/blob/master/1-js/04-object-basics/01-object/article.md

가능하시다면 대안을 남겨주세요.

**Comment by marocchino** [comment]
대괄호 표기법을 사용하실 때 프로퍼티 키는 문자열이외에 어떤 표현식의 평가 결과도 넣을 수 있습니다.

**Comment by Violet-Bora-Lee** [comment]
이슈를 남겨주신 분은 as opposed 를 […와는 대조적으로] 이라고 해석하셔서 어색하다고 생각하셨는데, 사전을 찾아보니  as opposed 는 […이 아니라]는 '양보'의 뜻도 가지고 있어서, 기존 번역문을 조금 수정하는 것으로 이슈 종결짓겠습니다.

(이슈 작성시 @SE0T00L 님과 함께 있었음)
