### ISSUE TITLE
Dashboard 수정권한 요청합니다

### ISSUE THREAD

**Issue by delta-kor** [javascript-tutorial/ko.javascript.info#443]
아직 번역되지 않는 튜토리얼 번역에 기여하겠습니다.
deltakbot1@gmail.com
감사합니다

**Comment by Violet-Bora-Lee** [comment]
안녕하세요.
글을 번역하시기 전에, 먼저 리뷰를 통해 전체적인 문장 스타일이나 한글화 관련 지식들을 습득해주시기 바랍니다.
글의 퀄리티를 높이기 위해 지속적으로 오역을 만드시거나 컨벤션(한국어 맞춤법, 리드미에 적힌 사항, Wiki페이지의 번역 모범 사례 등)을 지키지 않는 분들은 기여 중단을 권유드리고 있습니다.

권한 드렸습니다.

**Comment by delta-kor** [comment]
확인했습니다. 친절한 답변 감사합니다.
