### ISSUE TITLE
Dashboard 수정 권한 요청

### ISSUE THREAD

**Issue by HyunSangHan** [javascript-tutorial/ko.javascript.info#462]
공부하던 중, 해설 부분이 일부는 번역 / 일부는 번역되어 있지 않은 페이지를 발견하여 문득 번역에 참여하고 싶어졌습니다! 대시보드 수정 권한 부탁드립니다.

한 가지 질문이 있습니다.
제가 번역하고 싶다고 생각이 든 부분은 [메서드와 'this' 관련](https://github.com/javascript-tutorial/ko.javascript.info/blob/master/1-js/04-object-basics/04-object-methods/2-check-syntax/solution.md)입니다만, 대시보드를 보니 @Violet-Bora-Lee 님께서 담당자로 이미 되어있긴 하시더라고요. 반드시 대시보드상에서 비어있는 부분을 담당자로 예약 후에 이슈 등록하고 PR 진행해야 하나요?(사실, 이러한 프로세스를 파악하기 전에 이미 로컬에서 번역을 해버렸습니다.)

**Comment by Violet-Bora-Lee** [comment]
안녕하세요.
README파일 읽어보시고, GMAIL 아이디 적어주시면 대시보드 수정 권한 드리겠습니다.

네. 중복작업 방지를 위해 담당 파일 예약 후 번역을 진행하고 있습니다.
다만, this관련 글은 제가 2개밖에 하지 않았고, 아직 나머지 부분은 진행하지 않은상태인데, 로컬에서 번역을 진행하셨다고 하셔서 나머지 부분을 부탁드려볼까 합니다.

**Comment by HyunSangHan** [comment]
@Violet-Bora-Lee 
gustkd3@gmail.com 입니다! README 읽어보았고, 최대한 깔끔하게 작업해서 PR 진행해보겠습니다.
감사합니다.

**Comment by Violet-Bora-Lee** [comment]
권한 드렸습니다. 감사합니다 👍
