### ISSUE TITLE
대시보드 수정권한 요청

### ISSUE THREAD

**Issue by yourankim** [javascript-tutorial/ko.javascript.info#468]
안녕하세요, 한국어로 번역된 튜토리얼을 읽으면서 많은 도움을 얻고 있습니다. 저도 조금씩이나마 기여해보고 싶어서 권한 요청 드려봅니다.
지메일 계정은 youran.dev@gmail.com 입니다.
감사합니다!

**Comment by Violet-Bora-Lee** [comment]
환영합니다 :)
권한 드렸습니다.
