### ISSUE TITLE
계층 구조 띄어쓰기 통일

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#472]
DOM hierarchy에서 hierarchy를 일부 문서에선 `계층구조`, 일부 문서에선 `계층 구조`로 혼용하여 사용중임.

`계층 구조`로 통일하고자함.

cf. 용어집 등록 완료함

https://www.microsoft.com/en-us/language/Search?&searchTerm=hierarchy&langID=457&Source=true&productid=0

**Comment by JuYeong0413** [comment]
제가 작업하겠습니다. 😃

**Comment by Violet-Bora-Lee** [comment]
good first issue인만큼 처음 PR 보내주시는 분이 해주시면 좋을것 같습니다 :)
