### ISSUE TITLE
대시보드 권한 요청

### ISSUE THREAD

**Issue by jyoo** [javascript-tutorial/ko.javascript.info#482]
안녕하세요.

번역본 보다보니 굉장히 인상 깊었습니다. 주어진 메뉴얼을 참고하여 저도 기여 할 수 있으면 좋을 것 같아서 요청 드리게 되었습니다.
제 이메일은 jungsup.yoo@gmail.com 입니다.

감사합니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요.
권한드렸습니다.
리드미와 위키문서를 꼭 참고해주세요.
감사합니다 👍
