### ISSUE TITLE
대시보드 권한 요청

### ISSUE THREAD

**Issue by chayeoi** [javascript-tutorial/ko.javascript.info#484]
안녕하세요.
한국어 번역에 참여하고 싶어 권한 요청드립니다.
React 공식 문서, MDN 등 번역 경험 다수 있습니다.

chayeoikeem@gmail.com

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 환영합니다 :)

리드미에 있는 사항들을 꼭 정독하시고 기여해주세요

특히 위키문서의 번역 모범사례를 지켜주시기 바랍니다

권한 드렸습니다 참여해주셔서 감사드립니다
