### ISSUE TITLE
번역 작업 희망합니다.

### ISSUE THREAD

**Issue by eunajjing** [javascript-tutorial/ko.javascript.info#49]
안녕하세요, 오늘 women who code를 통해 해당 작업이 진행 중임을 소개 받았습니다. 저 또한 다른 분들의 귀한 노력으로 js를 배운 터라 번역에 함께 하고 싶어요!
email : high.euna@gmail.com

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 초대해드렸습니다
