### ISSUE TITLE
대시보드 수정 권한 요청

### ISSUE THREAD

**Issue by snowman39** [javascript-tutorial/ko.javascript.info#492]
안녕하세요! 의미 있는 프로젝트에 작게나마 기여할 수 있는 부분이 있다면 조금씩 참여하고 싶습니다.
README와 관련 가이드 읽어보았습니다.
kingzzang55@gmail.com입니다.
감사합니다 :)

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 권한드렸습니다.

기여자가 많아져서 조만간 대시보드 업데이트 규칙을 변경하려고하는데요,
새로운 작업을 하시게되면 대시보드 업데이트와 함께 이슈를 꼭 올려주세요.

감사합니다.
