### ISSUE TITLE
함수 표현식과 화살표 함수 번역 수정 제안

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#496]
https://ko.javascript.info/function-expressions-arrows

![image](https://user-images.githubusercontent.com/6451384/74863546-6a7a8880-5391-11ea-9631-05a152ecfd54.png)

위와 같은 번역 수정 제안이 있어서 good first issue로 등록합니다.
깃헙과 깃이 익숙하지 않으신데, 오픈소스에 컨트리뷰션 해보고 싶으신 분이 있으시면 내용을 반영한 PR을 보내주시면 될 것 같습니다.

**Comment by jenny5546** [comment]
제가 한 번 기여해보아도 될까요?

**Comment by Violet-Bora-Lee** [comment]
@jenny5546 넵 진행해주세요 :)

**Comment by Violet-Bora-Lee** [comment]
https://github.com/javascript-tutorial/ko.javascript.info/pull/497 에서 해결되어 이슈 종료합니다.
