### ISSUE TITLE
[배열] 번역 수정 제안

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#498]
![image](https://user-images.githubusercontent.com/6451384/74950512-91dd5e00-5442-11ea-90ed-721fb28dc098.png)
https://ko.javascript.info/array

위와 같은 번역 오류가 발견되어  수정 해야합니다.

good first issue 라벨을 달아 놓았으니, 깃이나 깃헙이 익숙하지 않은 분께서 작업해 주시면 좋을 것 같습니다.

**Comment by Violet-Bora-Lee** [comment]
초보자를 위한 팁!
커밋 메시지에 본 이슈 번호(#498)를 함께 적으면, PR생성시 본 이슈와 PR이 자동으로 연동됩니다.

**Comment by yoonkiwoong** [comment]
안녕하세요. 제가 찾은 오류, 제 손으로 수정해보고 싶은데 진행해도 괜찮을까요?

**Comment by Violet-Bora-Lee** [comment]
물론이죠 :)

**Comment by Violet-Bora-Lee** [comment]
배열 리뷰를 진행하며 이슈 해결하여 본 이슈를 종료하겠습니다.
