### ISSUE TITLE
[switch문] 오타 수정

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#501]
https://ko.javascript.info/switch#comment-4804025275

![image](https://user-images.githubusercontent.com/6451384/75088621-150dc980-5593-11ea-8dcf-933ab5d00721.png)

따옴표가 잘못 들어가 있어서 수정해야 합니다.

good first issue라벨을 달아 놓았으니, 깃이나 깃허브가 익숙하지 않은 분이 기여해주시면 좋을 것 같습니다.

**Comment by Violet-Bora-Lee** [comment]
초보자를 위한 팁!
커밋 메시지에 본 이슈 번호(#501)를 함께 적으면, PR생성시 본 이슈와 PR이 자동으로 연동됩니다.

**Comment by yourankim** [comment]
제가 수정할게요!

**Comment by Violet-Bora-Lee** [comment]
해결되어 이슈 종료하겠습니다.
