### ISSUE TITLE
Dashboard 수정 권한 요청

### ISSUE THREAD

**Issue by helloworld-hellohyeon** [javascript-tutorial/ko.javascript.info#503]
helloworld.hellohyeon@gmail.com 입니다 :)

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 권한 드렸습니다 :)

아직 관련 공지를 마련하지 않았는데, 새로운 번역 작업은 이슈를 등록해서 작업해주시면 좋을것 같습니다.

참여해주셔서 감사합니다 👍 👍 👍
