### ISSUE TITLE
Dashboard 수정 권한 요청

### ISSUE THREAD

**Issue by yoonkiwoong** [javascript-tutorial/ko.javascript.info#504]
안녕하세요. 주로 오타 수정 같은 간단한 작업에 기여하고 싶어서 Dashboard 수정 권한 요청 드립니다.

yoonkiwoong@me.com 

감사합니다!

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 권한 드렸습니다 :)
아직 관련 공지를 마련하지 않았는데, 새로운 번역 작업은 이슈를 등록해서 작업해주시면 좋을것 같습니다.

참여해주셔서 감사합니다 👍 👍 👍
