### ISSUE TITLE
[비교연산자] 문자열비교 설명 수정요청

### ISSUE THREAD

**Issue by becover** [javascript-tutorial/ko.javascript.info#507]
안녕하세요 :)
문자열 비교 설명에서 처음엔 **사전순**이라고 하고 밑에 다시 **사전순이 아니라 유니코드순**이라고 적혀있는데 혼동을 줄것 같아서 내용 수정 요청드립니다.

![image](https://user-images.githubusercontent.com/48202230/76144415-79687700-60c3-11ea-8e1d-4e9dfc146e1b.png)
![image](https://user-images.githubusercontent.com/48202230/76144420-82594880-60c3-11ea-8a44-af06b4e9dc03.png)

해당 페이지 링크 : [https://ko.javascript.info/comparison](https://ko.javascript.info/comparison)

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 혼동의 여지가 있네요.

그럼 아래쪽 상자의 타이틀을 '정확히는 유니코드 순입니다.'라고 하는게 어떨까요?

의견주세요.

**Comment by becover** [comment]
네 좋아요! :)

**Comment by Violet-Bora-Lee** [comment]
원문이 `Not a real dictionary, but Unicode order`이어서 `정확히는 사전순이 아니라 유니코드 순입니다.`으로 수정하겠습니다.

감사합니다 👍
