### ISSUE TITLE
[배열과 메서드] 번역 수정 요청

### ISSUE THREAD

**Issue by hmg0209** [javascript-tutorial/ko.javascript.info#511]
안녕하세요!
slice 의 내용 중 오역이 있어 수정요청드립니다.

[원문]
It returns a new array copying to it all items from index start to end (not including end).

> 이 메서드는 "start" 인덱스부터 ("end"를 제외한) "end"인덱스까지의 요소를 **포함하는 메서드를** 반환합니다.

-> 

> 이 메서드는 "start" 인덱스부터 ("end"를 제외한) "end"인덱스까지의 요소를 **복사한 새로운 배열을** 반환합니다.

원문을 참고하면, "복사한 새로운 배열을"으로 번역되어야 할 것 같습니다.
감사합니다.

https://ko.javascript.info/array-methods

**Comment by Violet-Bora-Lee** [comment]
안녕하세요.
이슈 제보해 주셔서 감사합니다.
가능하시다면 Pull Request도 보내주실수 있으신가요? 😃 

Let's make first PR! 👍

**Comment by Violet-Bora-Lee** [comment]
@hmg0209 
커밋은 잘 만들어주셨네요 👍 
이제 Pull Request를 보내주시면 될것같아요~

https://wayhome25.github.io/git/2017/07/08/git-first-pull-request-story/
이 글의 5번부터 참고하시면 됩니다~

**Comment by hmg0209** [comment]
@Violet-Bora-Lee 
남겨주신 페이지를 참고해 Pull Request를 보냈습니다! 🙏
말로만 들어본 PR을 처음 해보게 되서 기쁘네요~ 😀

**Comment by Violet-Bora-Lee** [comment]
크.. 멋지네요! 👍 
축하드립니다 :)
앞으로 더 많이 성장하시길 기원합니다 🥇 🥇 🥇
