### ISSUE TITLE
Dashboard 수정 권한 요청

### ISSUE THREAD

**Issue by chisishis** [javascript-tutorial/ko.javascript.info#513]
안녕하세요. 뜻깊은 일에 동참하고 싶어서 글 올립니다.
이메일은 chris.chang.dev@gmail.com 입니다.

readme.md와 관련 사항 잘 읽어보았습니다. 
감사합니다 :)

**Comment by Violet-Bora-Lee** [comment]
안녕하세요.
권한드렸습니다.
환영합니다 👍
