### ISSUE TITLE
md 파일들에 있는 ```코드``` 마크업문법에 오타

### ISSUE THREAD

**Issue by binkalos** [javascript-tutorial/ko.javascript.info#516]
```코드``` 마크업 문법에 ```갯수를 지키지 않은 오타들이 보입니다!
변수와 상수 챕터에서 ````smart header="let 이 문장을 포함하여 여러개가 확인됩니다.

**Comment by JuYeong0413** [comment]
`header` 안에 `code block`이 들어가는 경우 \` 기호가 4개씩 붙는 것으로 예상됩니다.  
말씀해주신 부분이 [84번째 줄](https://github.com/javascript-tutorial/ko.javascript.info/blob/master/1-js/02-first-steps/04-variables/article.md)인 것 같은데, [배포된 변수와 상수 페이지](https://ko.javascript.info/variables)에서 문제 없이 제대로 표시되고 있고 [튜토리얼 원문](https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/02-first-steps/04-variables/article.md)을 확인해보시면 해당 부분이 동일하게 \` 기호 4개로 되어 있습니다. 🙂

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 이슈 남겨주셔서 감사합니다.

본 튜토리얼의 마크업문서는 순수 마크업문서가 아니고, 커스터마이징 되어있습니다. 

서버 코드 클론받으신다음에 세팅해보시면 어떤 변형이 있는지 아실수 있을거에요.

이슈는 닫도록 하겠습니다.
