### ISSUE TITLE
Dashboard 수정권한 요청

### ISSUE THREAD

**Issue by SambaLim** [javascript-tutorial/ko.javascript.info#520]
안녕하세요.
번역에 동참하고 싶어 Issues에 글을 올립니다.
Readme.md를 읽고 Gitter와 카카오채팅방에도 접속해두었습니다.
감사합니다.😀

- 이메일: limsungho02@gmail.com

**Comment by Violet-Bora-Lee** [comment]
안녕하세요.
권한드렸습니다.
감사합니다 👍
