### ISSUE TITLE
Dashboard 권한 요청

### ISSUE THREAD

**Issue by LuiGee3471** [javascript-tutorial/ko.javascript.info#523]
안녕하세요
영어 원문부터 꾸준히 참고하던 가이드가 번역된 것을 보고 개선에 참여하고 싶어서 요청드립니다.

yjs3475@gmail.com 입니다

**Comment by Violet-Bora-Lee** [comment]
환영합니다 :)

수정권한 드렸습니다.

위키 문서등을 꼼꼼히 읽어보신 후 참여부탁드려요
