### ISSUE TITLE
Dashboard 권한 요청합니다.

### ISSUE THREAD

**Issue by choisohyun** [javascript-tutorial/ko.javascript.info#526]
안녕하세요! 자바스크립트 공부와 영어 공부를 함께 할 수 있을 것 같아 권한 요청합니다 :)

sohyun4283@gmail.com 입니다 감사합니다!

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 권한드렸습니다
리드미와 위키문서를 꼼꼼히 읽으시고 기여 부탁드립니다.
환영합니다 👍
