### ISSUE TITLE
[연산자] 오타 제보

### ISSUE THREAD

**Issue by hanameee** [javascript-tutorial/ko.javascript.info#527]
![image](https://user-images.githubusercontent.com/25149664/79694850-07807180-82ae-11ea-9de5-c22c88486dae.png)

안녕하세요 :)
번역해주신 좋은 자료로 공부하던 중, 사소한 오타가 발견되어 이슈 남깁니다. (이렇게 남기는 것이 맞나요?)

[연산자](https://ko.javascript.info/operators) 파트의 전위형, 후위형 증감 연산자 부분 설명에서
` 전위형은 증가/감소 후의 새로운 값을 반환하는 반면, 후위형은 증가/반환 전의 기존 값을 반환합니다.`
가 아니라,
`전위형은 증가/감소 후의 새로운 값을 반환하는 반면, 후위형은 증가/감소 전의 기존 값을 반환합니다.`
가 되어야 할 것 같습니다.

**Comment by Violet-Bora-Lee** [comment]
오타 제보 감사합니다.
혹시 가능하시다 PR보내주실수 있으실까요?
작게나마 오픈소스 기여 경험을 해보시길 권유드려봅니다.
