### ISSUE TITLE
[Chrome으로 디버깅하기] 오타 제보

### ISSUE THREAD

**Issue by hanameee** [javascript-tutorial/ko.javascript.info#529]
안녕하세요!

코드 품질의 [디버깅 부분](https://ko.javascript.info/debugging-chrome)을 공부하던 중, 오타로 보이는 부분을 발견하여 제보드립니다.

### 1.
크롬 디버깅 도구의 디버깅 영역 버튼 설명 과정의 **Step over** 부분에서, 

![image](https://user-images.githubusercontent.com/25149664/79720134-eb66e980-831a-11ea-9a11-38b8a9097344.png)

마지막 줄이 
`'Step’은 함수 호출 시 내부에서 어떤 일이 일어나는지 궁금하지 않을 때 유용합니다.`
가 아니라
`'Step over’은 함수 호출 시 내부에서 어떤 일이 일어나는지 궁금하지 않을 때 유용합니다.`
가 되어야 할 것 같습니다.

원문과 문맥을 참고한 결과 Step over이 중첩함수 내부로 진입하지 않기에, 마지막 줄은 Step이 아닌 Step over에 대한 내용인 것 같아 제보합니다.

### 2.
![image](https://user-images.githubusercontent.com/25149664/79721327-21a56880-831d-11ea-972d-c6e5a6ead3a1.png)
Heading에 명렁어 > 명령어 오타 있습니다.

### 3. 
![image](https://user-images.githubusercontent.com/25149664/79721549-7fd24b80-831d-11ea-8695-a92ca53879cf.png)
세 번째 bullet point 에서
`마우스 오른쪽 버튼을 클릭했을 때 나오는 중단점 제거 관련 기능을 중단점을 삭제할 수도 있습니다.`
가 아니라
`마우스 오른쪽 버튼을 클릭했을 때 나오는 "Remove breakpoint" 옵션을 통해 중단점을 삭제할 수도 있습니다.`
또는
`마우스 오른쪽 버튼을 클릭했을 때 나오는 중단점 제거 관련 기능을 통해 중단점을 삭제할 수도 있습니다.`
가 덜 어색할 것 같습니다.

추가적으로, 첫 번째 bullet point 도 `,`가 아닌 `.` 로 문장을 끝내는 것이 통일성 있을 것 같습니다.

+) 수정 사항을 제안할 때는 이렇게 항상 (1)이슈를 등록하고 (2)PR을 날리는 프로세스로 진행하면 될까요? 감사합니다.

**Comment by Violet-Bora-Lee** [comment]
간단한 수정사항은 바로 PR을 보내주셔도 됩니다.

이슈를 남기면 더 좋긴 해요 :)

**Comment by hanameee** [comment]
넵. PR 보내겠습니다. 감사합니다!
