### ISSUE TITLE
Dashboard 권한 요청

### ISSUE THREAD

**Issue by hanameee** [javascript-tutorial/ko.javascript.info#534]
안녕하세요! :D
공부 예정인 부분이 아직 번역되지 않은 것을 보고, 공부하는 김에 번역에 기여할 겸 요청드립니다!
hanameee@gmail.com 입니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 권한 드렸습니다 :)
기여해주셔서 감사합니다.

리드미와 wiki문서 꼭 읽어주시고 기여 부탁드릴게요
