### ISSUE TITLE
Dashboard권한요청합니다.

### ISSUE THREAD

**Issue by sujin-k** [javascript-tutorial/ko.javascript.info#538]
안녕하세요! 
번역에 참여하고싶어 이슈올립니다.
jinny39609@gmail.com입니다! 감사합니다:)

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 환영합니다 😄 
리드미와 위키 문서를 꼼꼼히 읽어보시고 기여 부탁드릴게요.
권한드렸습니다.
감사합니다.
