### ISSUE TITLE
Dashboard 권한 요청합니다.

### ISSUE THREAD

**Issue by yeoj1n** [javascript-tutorial/ko.javascript.info#539]
안녕하세요.
번역에 참여하고 싶습니다.
dev0yeoj1n@gmail.com
감사합니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 환영합니다 😄 
리드미와 위키 문서를 꼼꼼히 읽어보시고 기여 부탁드릴게요.
권한드렸습니다.
감사합니다.
