### ISSUE TITLE
어색한 번역

### ISSUE THREAD

**Issue by kwonmory** [javascript-tutorial/ko.javascript.info#544]
[클래스상속](https://ko.javascript.info/class-inheritance) 에서 ```자바스크립트는 '상속 클래스의 생성자 함수(derived constructor)와 그렇지 함수를 구분합니다.```
그렇지 함수를 구분합니다. 어색합니다. 

그렇지 -> 그렇지 않은

으로 변경해야되죠.

PR 할까요?

**Comment by Violet-Bora-Lee** [comment]
넵 PR보내주세요 :)
