### ISSUE TITLE
권한 요청 게시물

### ISSUE THREAD

**Issue by adk1245** [javascript-tutorial/ko.javascript.info#549]
안녕하세요 이 프로젝트에 처음으로 참여하면서 깃허브에 대해서 공부하고 싶습니다!. adk1245@gmail.com 수정 권한 요청드립니다. 감사합니다

**Comment by Violet-Bora-Lee** [comment]
안녕하세요.
권한 추가해드리려 했으나 구글 spreadsheet의 UI가 변경되면서 뭔가 잘 동작하지 않네요.
어제랑 오늘 작업해보았는데, 잘 안되어 조금 기다려주셨으면 합니다.

권한 추가되면 다시 댓글달도록 하겠습니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 권한추가드렸습니다.
본 프로젝트는 영한번역을 잘 하시는 분들이 적합한 프로젝트이기 때문에 깃헙 연습용으로는 조금 비효율적인것같습니다. 오픈소스 기여하시면서 자바스크립트 학습하고자 하시면 좋은 프로젝트이오니 참고하시어 기여하시면 될것같습니다. 감사합니다.
