### ISSUE TITLE
권한 요청

### ISSUE THREAD

**Issue by JiwoonKim** [javascript-tutorial/ko.javascript.info#55]
안녕하세요! 자바스크립트 번역에 참여하고자 하는 김지운입니다!
번역 활동에 참여할 수 있도록 대시보드 권한 허락해주시면 감사하겠습니다!

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 환영해요 🤗
구글 계정을 알려주시면 수정권한을 드릴게요

**Comment by JiwoonKim** [comment]
junebug0501@gmail.com 입니다! 감사합니다!

**Comment by Violet-Bora-Lee** [comment]
권한 부여해드렸습니다 :)
