### ISSUE TITLE
Dashbord 권한 요청합니다 !

### ISSUE THREAD

**Issue by ohdajung** [javascript-tutorial/ko.javascript.info#550]
안녕하세요 !
자바스크립트를 공부하면서 한글화 번역, 오타 수정 등을 참여하고 싶습니다 !
dajung9368@gmail.com 권한 요청 부탁드립니다 !!

**Comment by Violet-Bora-Lee** [comment]
안녕하세요.
권한 추가해드리려 했으나 구글 spreadsheet의 UI가 변경되면서 뭔가 잘 동작하지 않네요.
어제랑 오늘 작업해보았는데, 잘 안되어 조금 기다려주셨으면 합니다.

권한 추가되면 다시 댓글달도록 하겠습니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 권한추가드렸습니다.
리드미와 위키문서를 잘 읽어보시고 기여부탁드립니다.
감사합니다.
