### ISSUE TITLE
[정규 표현식] 유니코드 프로퍼티 번역어

### ISSUE THREAD

**Issue by LuiGee3471** [javascript-tutorial/ko.javascript.info#554]
유니코드 관련 문서 번역 중 유니코드 프로퍼티의 번역어 선택 문제가 있습니다. 한글에서는 사용하지 않는 프로퍼티가 많아 널리 쓰이는 번역어가 없거나 단순 독음을 사용하고 있는 경우가 많은데요.
예) titlecase: Lord of the Rings처럼 전치사, 관사 등을 제외하고 첫 글자를 대문자로 표현하는 방식

참고할 만한 번역을 찾던 중 마이크로소프트의 닷넷 번역 문서에 유니코드 프로퍼티를 다루는 열거형의 번역 문서([https://docs.microsoft.com/ko-kr/dotnet/api/system.globalization.unicodecategory?view=netcore-3.1](url))가 있었습니다. 

이 문서의 번역어를 사용해 문서 번역을 진행해도 될지 이슈를 올려봅니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 메일 대신 앱으로 노티피케이션을 받도록 해놓았는데, 뭔가 문제가 있는지 푸시 알람이 잘 오지 않아 이슈 확인이 늦었습니다.

널리 쓰이는 번역어가 없는 경우엔 IT분야에선 음차번역을 하거나 번역하지 않는 방법을 주로 택하는데, 유사한 상황인것 같습니다.

구체적으로 어떤 부분에서 고민하시는지 예시를 들어주실수 있으신가요? 올려주신 이슈만으로는 **'어떤 용어를 어떻게 번역하겠다'** 라는게 와닿지 않아서요.

**Comment by LuiGee3471** [comment]
9-3의 61번 줄 ~ 97번 줄의 내용입니다.

https://www.fileformat.info/info/unicode/category/Pi/list.htm
https://www.compart.com/en/unicode/category/Sk
https://www.fileformat.info/info/unicode/category/Pc/list.htm

위의 링크에 있는 유니코드 문자가 예시인데 한국어에서는 일부만 쓰이거나 아예 쓰이지 않는 문자 개념이라 저런 문자의 집단을 가리키는 일반적인 번역어가 없는 것으로 보입니다. 그런 상황에서 모든 프로퍼티가 일치하는 닷넷의 열거형이 있어서 해당 문서를 참고하려고 했습니다.

**Comment by Violet-Bora-Lee** [comment]
아, 이해되었습니다.
좋네요! MS문서대로 번역하시면 될것같습니다. 👍

**Comment by LuiGee3471** [comment]
네 그러면 참고해서 번역하겠습니다
