### ISSUE TITLE
private, protected 프로퍼티와 메서드 > 예제 실행 에러

### ISSUE THREAD

**Issue by j29130811** [javascript-tutorial/ko.javascript.info#556]
주소
https://ko.javascript.info/private-protected-properties-methods

1. 읽기 전용 프로퍼티 예제
SyntaxError: missing ) after argument list 에러 발생

2. private 프로퍼티 예제
SyntaxError: Unexpected token '('

3. #waterAmount 생성 예제
SyntaxError: Private field '#waterAmount' must be declared in an enclosing class

**Comment by Violet-Bora-Lee** [comment]
![image](https://user-images.githubusercontent.com/6451384/83352652-0a2fb580-a388-11ea-9608-aca56bedda76.png)

![image](https://user-images.githubusercontent.com/6451384/83352662-1e73b280-a388-11ea-873d-9e1d150de423.png)

![image](https://user-images.githubusercontent.com/6451384/83352668-2df2fb80-a388-11ea-9e88-7ccedbe33b2c.png)

**Comment by Jaewoook** [comment]
2, 3번 에러에 대해서는 아직 브라우저에서 지원하지 않아 에러가 발생하는 것으로 보입니다. (영문 페이지에서도 똑같은 에러메시지 출력되는 것을 확인함) 특히 2번 에러는 함수 이름에 **#** 기호가 붙어있으면 함수 이름으로 인식하지 못해 에러가 나는 것으로 보입니다. (macOS, 크롬 v83 기준)

**Comment by Violet-Bora-Lee** [comment]
첫 번째 예시는 번역시 불필요한 백틱이 들어간 실수가 있었습니다. @Jaewoook 님께서 올려주신 PR에 의해 수정되었습니다.

나머지 두 예시는 에러가 발생하는것이 당연해서 수정하지 않아도 될 것 같습니다.

이슈 종료하겠습니다.
