### ISSUE TITLE
[오타 제보] 홈->코어 자바스크립트->자바스크립트 기초

### ISSUE THREAD

**Issue by ccf05017** [javascript-tutorial/ko.javascript.info#571]
안녕하세요, 번역해주신 코어 자바스크립트 튜토리얼 감사히 잘 보고 있습니다.
학습 도중 오타를 발견해서 제보드립니다. 시간 되실 때 수정해주시면 감사하겠습니다.

내용은 아래와 같습니다.

- URL 위치: https://ko.javascript.info/strict-mode
- 내용:
![스크린샷 2020-06-12 오전 10 15 38](https://user-images.githubusercontent.com/30560659/84454573-d1e87b00-ac95-11ea-87da-54b24425349d.png)

**Comment by Violet-Bora-Lee** [comment]
맥에서 작업하다보면 저렇게 꼭 끝글자가 사라져버리네요 ㅠㅠ

제보해주셔서 감사합니다. 

오픈소스 기여에 참여하고 싶은 분들을 위하여 good first issue 라벨 달아놓겠습니다.
