### ISSUE TITLE
Dashboard 챕터의 순서와 링크

### ISSUE THREAD

**Issue by LuiGee3471** [javascript-tutorial/ko.javascript.info#579]
정규 표현식 관련 챕터 번역 상태를 변경하려다가 Dashboard에 있는 정규 표현식 챕터가 실제 사이트의 챕터 순서와 크게 다른 것을 발견했습니다.

순서가 같다고 생각하고 작업을 진행했더니 작업 결과 링크나 번역 상태가 뒤죽박죽 섞여버렸네요😥

일부 챕터는 내용이 바뀌거나 다른 챕터와 합쳐져 링크와 이어지는 페이지가 없는 경우도 있고 아예 Dashboard에는 없는 챕터도 있었습니다.

챕터 제목과 링크 컬럼은 수정 권한이 잠겨있어서 이슈에 수정 요청 드립니다.

다른 파트에도 그런 경우가 있나 확인해봤는데 '자바스크립트 기초' 파트에서 'alert, prompt, confirm을 이용한 상호작용' 챕터가 실제 챕터와 순서가 다르게 Dashboard에 위치해있기는 하지만 실제 반영 자체는 문제 없는 것이 하나였고 'UI Events' 파트에서 'Pointer Events'가 영어 사이트에는 있는데 한국어 사이트와 Dashboard에는 없는 두 가지 외에는 없었습니다.

**Comment by Violet-Bora-Lee** [comment]
계속 목차가 업데이트되어서 갱신이 안된부분이 있을거예요.
제보해주셔서 감사합니다.

구글 스프레드시트 사용이 익숙하시다면 제가 권한을 드려도 될까요?

권한을 막아놓은 이유가, 이전에 권한 풀어놨을 때 history tracking이 되지 않게 실수로 건드시는 분들이 꽤 있으셔서 막아놓게 되었거든요.

**Comment by LuiGee3471** [comment]
많이 익숙하다고 할수는 없는데 꼭 지켜야 하는 사항 이야기해주시면 방법 찾아가면서 수정해보겠습니다.

**Comment by Violet-Bora-Lee** [comment]
목차부분 수정 권한 드렸습니다 :)

**Comment by Violet-Bora-Lee** [comment]
저도 빠르게 눈으로 훓어보면서 현재 번역하시는 정규 표현식 위쪽에 목차 수정할 것들 있으면 수정해놓도록 할게요

**Comment by Violet-Bora-Lee** [comment]
정규표현식쪽도 수정해놓았습니다.
