### ISSUE TITLE
[오타 제보] '자바스트립트 기초' 챕터의 '기본 연산자와 수학'에서 오타를 발견하였습니다. 

### ISSUE THREAD

**Issue by whaleit** [javascript-tutorial/ko.javascript.info#581]
먼저 번역해주신 튜토리얼을 잘 보고 있습니다. 좋은 자료를 번역해주셔서 감사합니다. 
공부하다가 작은 오타를 발견해서 보고 드립니다. 

URL 위치: https://ko.javascript.info/operators (이 페이지의 '복합 할당 연산자' 부분입니다.)
내용: 아래 빨간 네모 부분이 += 가 아니라 *=여야 할 것 같습니다.
![스크린샷_2020-06-16_오후_12_46_27](https://user-images.githubusercontent.com/40480882/84729987-fadb7980-afcf-11ea-96c1-5fb9266926d3.jpg)

**Comment by Violet-Bora-Lee** [comment]
제보 감사합니다 :)

가능하시면 PR날려주셔도 좋을것같아요.

아니라면 깃헙 익숙하지 않으신 분들이 기여할 수 있도록 good first issue라벨 달아놓겠습니다.
