### ISSUE TITLE
자료구조와 자료형의 문자열 챕터에의 따옴표 내용 부분 오타

### ISSUE THREAD

**Issue by moonkii** [javascript-tutorial/ko.javascript.info#582]
안녕하세요:)

[문자열 챕터의 따옴표](https://ko.javascript.info/string#ref-528) 설명 부분에서 백틱을 설명할 때 오타를 발견해서 이슈 남깁니다.

오타 부분은 다음과 같습니다.
![image](https://user-images.githubusercontent.com/46776329/84854989-fd0c0980-b09d-11ea-94b0-22fc30abe534.png)

해당 부분을 `여러 줄에 문자열을 만들 수 없습니다.` 또는 ` 여러 줄 짜리 문자열을 만들 수 없습니다.` 라고 수정해야 할 것 같습니다.

**Comment by Violet-Bora-Lee** [comment]
제보 감사합니다.

맥에서 작업하다보면 글씨가 하나씩 잘릴때가 많네요.

저도 주의해서 해야겠습니다.

good first issue라벨 달아놓겠습니다.

가능하시면 수정하셔서 PR 날려주셔도 좋습니다 :)
