### ISSUE TITLE
[오번역] 배열 in 자료구조와 자료형

### ISSUE THREAD

**Issue by shb0107s** [javascript-tutorial/ko.javascript.info#583]
안녕하세요. 공부하던 중 해석이 잘못된 부분이 있는 것 같아 이슈 남깁니다.

"배열의 내부 동작 원리" 파트에

> 이렇게 배열은 자바스크립트의 일곱 가지 원시 자료형 중 하나인 객체형에 속하기 때문에 객체처럼 동작합니다.

라는 문장이 있는데 영어 본문에는

> Remember, there are only 7 basic types in JavaScript. Array is an object and thus behaves like an object.

이라고 작성되어있습니다.

이전 Javascript Fundamentals의 Data types에서 8개의 data type 중 object는 primitive가 아닌 special case라고 설명했던 점을 미루어 봤을 때, "배열은 원시 자료형이 아닌 객체형에 속하기 때문에, 객체와 같이 동작한다"는 의미에 더 가깝지 않나 생각합니다.

항상 잘 읽고 있습니다. 감사합니다.

**Comment by Violet-Bora-Lee** [comment]
아래와 같이 수정해서 올려주실 컨트리뷰터를 기다리겠습니다 :)

> 이렇게 배열은 자바스크립트의 일곱 가지 원시 자료형에 해당하지 않고, 원시 자료형이 아닌 객체형에 속하기 때문에 객체처럼 동작합니다.

**Comment by Violet-Bora-Lee** [comment]
@shb0107s 인생 첫번째 PR도 도전해보세욧 :)

**Comment by OMEGA-Y** [comment]
제가 수정해보겠습니다!!

**Comment by Violet-Bora-Lee** [comment]
@OMEGA-Y 님께서 수정해주셔서 이슈 종료합니다
