### ISSUE TITLE
권한 요청 드립니다.

### ISSUE THREAD

**Issue by bangina** [javascript-tutorial/ko.javascript.info#589]
https://javascript.info/focus-blur 문서의 번역 작업 시작하고자 하니 dashboard 수정 권한 부여해주시면 고맙겠습니다.

email : bbangina@gmail.com

**Comment by Violet-Bora-Lee** [comment]
권한 드렸습니다.

리드미와 위키에 있는 모범 사례를 꼭 확인해보시고 기여 부탁드립니다.
