### ISSUE TITLE
대시보드 수정 권한 요청합니다

### ISSUE THREAD

**Issue by dev-dain** [javascript-tutorial/ko.javascript.info#594]
안녕하세요?
문서를 보다가 [기본 연산자와 수학](https://ko.javascript.info/operators#tasks) 글에 마지막 문제가 번역되어 있지 않아 간단한 문제라 직접 옮겨보고 싶습니다.
현재 해당 문서는 대시보드에는 과제/해답 번역이 Finished이고 2차 리뷰까지 Finished 상태인데요. 권한을 받게 되면 저는 3차 리뷰에 제 이름을 쓰면 될지도 궁금합니다.
제 메일 주소는 dev.dain.k@gmail.com 입니다.
감사합니다. ^^

**Comment by Violet-Bora-Lee** [comment]
안녕하세요
과제가 추가되었나보네요
3차 리뷰에 쓰시고 진행하시면 될것같습니다.
권한드렸습니다 :)
