### ISSUE TITLE
[권한요청] 대시보드 권한요청 부탁드립니다.

### ISSUE THREAD

**Issue by kellywoo** [javascript-tutorial/ko.javascript.info#602]
@Violet-Bora-Lee

안녕하세요! 
번역작업에 참여하고 싶습니다.
대시보드 권한 부탁드리겠습니다.

kelly.kh.woo@gmail.com 입니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 권한드렸습니다.
환영합니다 :)

리드미와 위키의 모범사례를 꼭 1회이상 정독한후 작업부탁드려요
