### ISSUE TITLE
[권한요청] 대시보드 수정 권한 부탁드려요!

### ISSUE THREAD

**Issue by hyemmie** [javascript-tutorial/ko.javascript.info#607]
안녕하세요!
번역 작업에 참여하고 싶은데 dashboard에 권한 추가해주시면 감사하겠습니다.
lhm07100@gmail.com 입니다!

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 권한드렸습니다. 환영해요 :)

리드미와 위키의 모범사례를 꼭 1회이상 정독하신 후 작업부탁드려요
