### ISSUE TITLE
위키 설치 방법 5번 항목에 대한 이슈

### ISSUE THREAD

**Issue by Canine89** [javascript-tutorial/ko.javascript.info#613]
[여기](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0#%EC%84%A4%EC%B9%98-%EB%B0%A9%EB%B2%95)의 5번 항목에 대해서 어떤 저장소를 포크떠야 하는지 명시하면 조금 더 좋은 문서가 될 것 같습니다.

**Comment by Violet-Bora-Lee** [comment]
@Canine89 님, 일단 위키는 수정했습니다.
다시한번 봐주시고, 잘 이해가 되는지 알려주실수 있으실까요?

**Comment by Canine89** [comment]
@Violet-Bora-Lee 
네 확인했습니다. 괜찮은 것 같습니다.
