### ISSUE TITLE
[권한요청] 대시보드 수정 권한 요청드립니다

### ISSUE THREAD

**Issue by hyesoo5115** [javascript-tutorial/ko.javascript.info#617]
안녕하세요 이번 컨트리뷰톤에 참여하고 있는 김혜수라고 합니다 !! 대시보드 수정 권한 요청드립니다 :)

메일 계정 hyesoo5115@gmail.com 입니다

**Comment by Violet-Bora-Lee** [comment]
권한 드렸습니다.
환영합니다 👍
