### ISSUE TITLE
block에 대한 번역어 통일

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#62]
원문 block이 블럭, 블록 등으로 쓰이고있는데 이에 대한 번역어 통일이 필요함

**Comment by singularity-code** [comment]
검색결과 "블럭"은 1개의 경우에, "블록"은 77 번 사용되고 있고
다른 문서들도 "블록"을 더 많이 사용하고 있으니 "블럭"을 사용하는 하나의 케이스를 수정하는편이 어떨까요?

"블럭"을 사용하고 있는 파일: 
2-ui/1-document/02-dom-nodes/article.md

L190: 2. 요소 노드(element nodes) -- HTML 태그들, 트리를 만드는 블럭.

**Comment by Violet-Bora-Lee** [comment]
Good first issue는 오픈소스에 처음 pr을 날리시는 분들을 위한 용도로 만들었습니다. :) 달아주신 코멘트를 참고하여 초심자들이 잘 pr하실것 같습니다. 감사합니다.

**Comment by happhee** [comment]
제가 작업하겠습니다.

**Comment by happhee** [comment]
블록으로 통일되어 있습니다.
Issue closing 해주세요.

**Comment by Violet-Bora-Lee** [comment]
확인되었습니다. 이슈 클로징하겠습니다.
