### ISSUE TITLE
논리 연산자 오번역

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#621]
윤영우님께서 댓글을 통해 남겨주신 오번역 내용입니다.

> 본문 내용 중 단락평가 부분에서
> 
> true || alert("not printed");
> false || alert("printed");
> 첫 번째 줄의 || 연산자는 true를 만나자마자 평가를 멈추기 때문에 alert가 실행되지 않습니다.
> 
> 단락 평가는 조건이 truthy일 때만 명령어를 실행하고자 할 때 자주 쓰입니다. <- 이 부분이 반대가 아닌가요?
> 단락 평가는 조건이 'truthy가 아닐 때만' 명령어를 실행하고자 할 때 자주 쓰입니다. 가 되야 할거 같아요.

**단락 평가는 조건이 falsy일 때만 명령어를 실행하고자 할 때 자주 쓰입니다** 이렇게 수정해주실 분이 있으시면 PR 남겨주세요

**Comment by Seungsin** [comment]
제가 하겠습니다!
