### ISSUE TITLE
[용어 통일] 매개변수, 인자(또는 인수)

### ISSUE THREAD

**Issue by Canine89** [javascript-tutorial/ko.javascript.info#633]
https://www.google.com/search?q=%EC%9D%B8%EC%9E%90+%EB%A7%A4%EA%B0%9C%EB%B3%80%EC%88%98&oq=%EC%9D%B8%EC%9E%90+%EB%A7%A4%EA%B0%9C%EB%B3%80%EC%88%98&aqs=chrome..69i57.1584j0j4&sourceid=chrome&ie=UTF-8

검색 결과에서 보듯 매개변수와 인자(또는 인수)는 서로 다른 것을 지칭합니다. 매개변수는 말 그대로 함수 선언 시 사용되는 변수를 말하고, 인자는 함수 실행 시 전달하는 값 자체를 말합니다. 많은 개발자가 이를 혼용하는데요(그렇게 어색하지도 않습니다만) 그러나 여러 사람이 참여하는 프로젝트인 만큼 이 둘은 이왕이면 구분하면 좋겠습니다. 다음 예를 참고해 주세요.

예1: 함수 func의 매개변수 a, b에 인자 1, 2를 각각 전달합니다.
예1: 함수 func의 매개변수 a, b에 인수 1, 2를 각각 전달합니다.

**Comment by Violet-Bora-Lee** [comment]
#508 과 중복이슈이기 때문에 종료합니다.
