### ISSUE TITLE
[오번역] 자바스크립트 기초의 Hello, world! 내용

### ISSUE THREAD

**Issue by OMEGA-Y** [javascript-tutorial/ko.javascript.info#635]
안녕하세요. 자바스크립트 기초의 Hello, world! 내용을 읽다가 오번역 된 부분이 있는 것 같아 남깁니다. 

외부 스크립트의 주의에 대한 내용 중 '이를 통해 트래픽이 절약되고 웹 페이지의 실 속도가 빨라집니다.'라는 문장에서 '실 속도'보다는 '실제 속도'라고 번역하는 것이 더 자연스러운 것 같습니다. 또 맞춤법 검사기에서도 '실 속도'라고는 안 쓰고 '실속도'로 합성어로 취급하여 띄어쓰기 없이 사용합니다.

**Comment by dazzel3** [comment]
안녕하세요. 실속도 보다는 실제 속도가 더 자연스러운 것을 반영하여 수정PR하겠습니다.

**Comment by OMEGA-Y** [comment]
https://github.com/Violet-Bora-Lee
