### ISSUE TITLE
[권한요청] 대시보드 수정 권한 요청드립니다.

### ISSUE THREAD

**Issue by KimHunJin** [javascript-tutorial/ko.javascript.info#639]
안녕하세요. 컨트리뷰톤 멘티 김헌진입니다.

대시보드 수정 권한 요청드립니다.
메일은 ysg01129@gmail.com 입니다.

감사합니다.

**Comment by Violet-Bora-Lee** [comment]
권한드렸습니다.
환영합니다 👍
