### ISSUE TITLE
[권한요청] 대시보드 수정 권한 요청드립니다.

### ISSUE THREAD

**Issue by DavidYang2149** [javascript-tutorial/ko.javascript.info#645]
안녕하세요.
양홍석입니다.
번역작업에 참여하고자 권한 신청을 드립니다. 
대시보드 수정 권한 요청드립니다.

github : davidyang2149
gmail : davidyang2149@gmail.com

감사합니다.

**Comment by Violet-Bora-Lee** [comment]
권한드렸습니다.
환영합니다 👍
