### ISSUE TITLE
주술구조가 있는 문장 끝의 :(콜론) 처리

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#66]
영어의 경우 문장 내 콜론을 쓰는 것이 허용되고, 원문에서도 이를 이용하고 있음.
하지만 한국어의 경우 문장 끝에 콜론을 쓰는 것이 부자연스러움.

튜토리얼 번역 초반엔 이를 인지하지 못하고 원문의 문장 끝에 있는 콜론을 그대로 차용하여 사용했으나, 이 부분을 바로잡아야 할 필요가 있음.

**Comment by singularity-code** [comment]
이것은 충돌날수도 있으니 큰 폴더별로 맡았던 분이 해당 폴더내의 파일들만 수정해서 push하는 것이 어떨까요?

예를들면 저는 1-js/06-advanced-functions 폴더내에서 콜론이 사용된부분 제거후 #66번 이슈에 commit

**Comment by Violet-Bora-Lee** [comment]
좋은의견인것 같습니다. 큰 폴더별로 주 번역자가 없는 경우에는, 리뷰자가 해당 이슈에 관한 사항을 수정하는것도 괜찮을 것 같습니다.

**Comment by sojeongw** [comment]
해보겠습니다!

**Comment by Violet-Bora-Lee** [comment]
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%8C%8D%EC%A0%90%EC%9D%80-%EA%B1%B0%EC%9D%98-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

위키 문서 업데이트 진행하였습니다.
