### ISSUE TITLE
Part1 4.1 객체 추가번역

### ISSUE THREAD

**Issue by Seungsin** [javascript-tutorial/ko.javascript.info#661]
Part1 4.1 객체 부분 추가 번역 진행하겠습니다!

> Object with const can be changed

이 부분 번역 진행하겠습니다!

**Comment by sowon-dev** [comment]
@Seungsin 님이 이슈번호 #661 로 번역하신다고 남기셨는데 @C17AN 님도 #685 로 동일한 부분 번역한다고 이슈등록하신 것같아요.  @C17AN 님은 PR번호 #686 로 해당 이슈를 이미 번역 완료 하신 것 같아요. 혹시 중복으로 번역하실까봐 말씀드립니다. 확인부탁드려요

**Comment by C17AN** [comment]
> @sowon-dev 엥??? 그렇네요!!

제 PR을 close 하도록 하겠습니다 ㅠ__ㅠ
일이 복잡해지기 전에 봐주셔서 감사드려요!! 😆

**Comment by Seungsin** [comment]
@sowon-dev 앗 봐주셔서 감사합니다!!

**Comment by Seungsin** [comment]
@C17AN 혹시 번역 꽤 진행하신거면 그냥 제가 다른 부분 하겠습니다!! 기껏 하신거면 날리기 아깝잖아요ㅜㅜ 저는 아직 제대로 시작을 못해서 양보해드릴 수 있어요!

**Comment by C17AN** [comment]
@Seungsin 아니에요!!! 이건 제 잘못이기도 하구 ㅜㅜㅜ
이미 PR도 닫았으니 제가 다른 글을 찾아볼게요!

혹시 필요하시다면 #686번 커밋은 번역할 때 참고하셔도 괜찮아요!!
그럼 좋은 하루 보내세요~~! 😄

**Comment by Seungsin** [comment]
PR확인해보니 @GreatLaboratory님도 이 부분 번역 진행하고 계신 것 같아 제 issue는 닫도록 하겠습니다!

**Comment by GreatLaboratory** [comment]
@Seungsin @C17AN 앗.. 죄송합니다ㅠㅠ 제가 기존에 open된 issue들을 제대로 확인하지 못하고 PR을 진행해버렸네요...
다음부턴 주의하도록 하겠습니다.. 정말 죄송합니다ㅜㅜ
