### ISSUE TITLE
[오번역] Part1 - [2.12 null 병합연산자 '??']

### ISSUE THREAD

**Issue by OMEGA-Y** [javascript-tutorial/ko.javascript.info#673]
**원문** : The precedence of the ?? operator is rather low: 5 in the MDN table.

**현재** :  ??의 연산자 우선순위는 7로 꽤 낮습니다.

**수정방향** :  7을 5로 수정해야 할 것 같습니다.

**Comment by kyujonglee** [comment]
제가 PR 날리도록 하겠습니다 :)
