### ISSUE TITLE
[권한요청] 대시보드 수정 권한 요청드립니다

### ISSUE THREAD

**Issue by ccppoo** [javascript-tutorial/ko.javascript.info#677]
무소속, 공군현역 번역참가하고 싶습니다
shmishmi79@gmail.com

**Comment by Violet-Bora-Lee** [comment]
권한 드렸습니다

리드미와 위키 문서를 꼭 정독하시고 참여해주세요

감사합니다 👍

**Comment by ccppoo** [comment]
@Violet-Bora-Lee 스프레드시트 내 참여자로 등록되어있지만, 수정권한이 주어지지 않았습니다. 확인부탁드립니다.

**Comment by ccppoo** [comment]
@Violet-Bora-Lee 스프레드시트 내 참여자로 등록되어있지만, 수정권한이 주어지지 않았습니다. 확인부탁드립니다.

**Comment by Violet-Bora-Lee** [comment]
다시 해드렸는데 확인부탁드립니다

**Comment by ccppoo** [comment]
네 확인했습니다 감사합니다!
