### ISSUE TITLE
[권한요청] 대시보드 수정 권한 요청합니다.

### ISSUE THREAD

**Issue by marco0332** [javascript-tutorial/ko.javascript.info#702]
## Gmail 아이디
marco2520332@gmail.com

컨트리뷰톤 참가자 이기인입니다.

**Comment by Violet-Bora-Lee** [comment]
권한드렸습니다

**Comment by marco0332** [comment]
@Violet-Bora-Lee 
링크 공유 메일에 포함된 링크를 타고 들어가도 여전히 보기 전용으로 들어가집니다.
확인 부탁드립니다.
