### ISSUE TITLE
[작업할 내용 공유] Part 3 Binary data, files (Blob) 번역하겠습니다.

### ISSUE THREAD

**Issue by ccppoo** [javascript-tutorial/ko.javascript.info#714]
작업할 내용 : Part 3 Binary data, files (Blob)

그리고 완성하고 이어서 Part 3 Binary data, files (File and FileReader) 번역해보도록 하겠습니다.

**Comment by Violet-Bora-Lee** [comment]
죄송하지만 한 글씩 번역을 해주세요. 

그리고 리드미 파일과 위키 문서를 정독하시고 기여해주세요.

현재 전역중이시라면 기여에 도움될만한 책을 추천드릴게요.

'초급 번역패턴 500 플러스' 이 책을 읽어보시고 본격적으로 기여 부탁드립니다.

지금 올려주신 최초 PR을 보니 문장 구성이나 번역에 대한 훈련이 안되있으셔서, 쓰기 관련 코멘트가 많아지고 있습니다.
