### ISSUE TITLE
primitive에 대한 번역어 통일

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/ko.javascript.info#72]
현재, primitive(s)는 `원시 값`으로 번역하기로 합의되었고, 용어집에 등록되어있는 상황입니다.

띄어쓰기 없이 `원시값`으로 통일하도록 합시다.

- [ ] 원시값으로 모든 문서 업데이트

- [ ] 용어집 업데이트

**Comment by rnjstjdgh** [comment]
제가 하겠습니다

**Comment by Violet-Bora-Lee** [comment]
작업 완료 확인되어 이슈 클로징하겠습니다.
