### ISSUE TITLE
[대시보드 권한 요청] 대시보드 수정 권한 요청합니다

### ISSUE THREAD

**Issue by kmin-jeong** [javascript-tutorial/ko.javascript.info#742]
안녕하세요! 저는 김민정이라고 합니다!모던 자바스크립트 튜토리얼에서 모르는 부분을 보다가 도움을 받아서 알게 되었습니다.
그래서 튜토리얼에 기여해 보고 싶어서 찾아보다가 발견하였습니다! 
번역작업에 참여하고자 권한 신청을 드립니다.
대시보드 수정 권한 요청드립니다.
desk535353@gmail.com
github id: kmin-jeong

**Comment by Violet-Bora-Lee** [comment]
권한드렸습니다. 환영합니다 👍
