### ISSUE TITLE
[대시보드 권한 요청]대시보드 권한 요청 드립니다!

### ISSUE THREAD

**Issue by yule93** [javascript-tutorial/ko.javascript.info#750]
## Gmail 아이디
**dbfm2222@gmail.com**

안녕하세요! 권한 요청 부탁드리고 싶습니다! 번역에 참여하고 싶어요 :D !!
감사합니다!

**Comment by Violet-Bora-Lee** [comment]
권한드렸습니다.
환영합니다 👍

**Comment by yule93** [comment]
감사합니다!! 좋은 하루 되세요!!😆
