### ISSUE TITLE
[신규 번역] 파트1 4.6 옵셔널 체이닝 '?.' 미번역분 번역

### ISSUE THREAD

**Issue by sowon-dev** [javascript-tutorial/ko.javascript.info#784]
### 작업할 내용
ex) [Part 1. 1.1 An Introduction to JavaScript](https://javascript.info/intro)에 대한 번역
[Part 1. 4.6 옵셔널 체이닝 '?.'](https://ko.javascript.info/optional-chaining#ref-405)에 대한 원문 추가로 인해 미번역된 `?.앞의 변수는 꼭 선언되어 있어야 합니다` 부분 번역하겠습니다. 대시보드에 댓글 달았습니다.
원문 업데이트 부분(https://github.com/javascript-tutorial/en.javascript.info/commit/1f0fcb7de6eaf288daf5b035c74b77c7f0644759) 꼼꼼히 보고 반영하겠습니다.

**Comment by Violet-Bora-Lee** [comment]
해당 작업 완료되어서 이슈 클로징 합니다.
참여해주셔서 감사합니다 👍
