### ISSUE TITLE
[대시보드 권한 요청] 

### ISSUE THREAD

**Issue by JimmyJoo** [javascript-tutorial/ko.javascript.info#868]
## Gmail 아이디

jimmyjoo1029@gmail.com

안녕하세요! 번역에 참가하고 싶습니다.
대시보드 수정 권한요청드립니다. 🙏

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 권한드렸습니다.
기여 가이드와 위키문서 숙지하신 후 기여부탁드려요
환영합니다 👍
