### ISSUE TITLE
대시보드 권한요청

### ISSUE THREAD

**Issue by creduo** [javascript-tutorial/ko.javascript.info#87]
안녕하세요

자바스크립트 번역에 참여하고자 하는 박주혁 입니다
번역 활동에 참여할 수 있도록 권한 추가해주세요 ~

creduo@gmail.com 입니다.

**Comment by Violet-Bora-Lee** [comment]
환영합니다 주혁님 :)
권한 드렸습니다.
앞으로 즐겁게 같이 기여해봐요~
