### ISSUE TITLE
[대시보드 권한 요청] 권한 요청드립니다.

### ISSUE THREAD

**Issue by ghleokim** [javascript-tutorial/ko.javascript.info#875]
## Gmail 아이디
gh.leokim@gmail.com

안녕하세요. 번역에 참여하고 싶습니다.

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 권한드렸어요
컨트리뷰팅 가이드와 위키문서 꼼꼼히 읽어보신 후 기여 시작 부탁드릴게요
