### ISSUE TITLE
[오타수정] 제너레이터 본문내 전개 문법 링크 깨짐

### ISSUE THREAD

**Issue by yunyong** [javascript-tutorial/ko.javascript.info#917]
## 원문

![스크린샷 2020-10-20 오후 11 28 14](https://user-images.githubusercontent.com/7077013/96600483-f29f9c00-132b-11eb-86bf-64df7defc44b.png)

![스크린샷 2020-10-20 오후 11 25 58](https://user-images.githubusercontent.com/7077013/96600414-dd2a7200-132b-11eb-9052-773e7c8f6721.png)

## 오타수정
```
(전개 문법에 대한 자세한 설명은 [](info:rest-parameters-spread#spread-syntax)에서 볼 수 있습니다.)
```
로 수정 되어야 할 것 같아요.

## 이슈

예전 링크가 걸려있는건지, 존재하지 않는 링크로 인해 위와 같이 나오고 있습니다.

## Pull Request(PR)를 통해 수정할 의향이 있습니까?
넵

**Comment by Violet-Bora-Lee** [comment]
이슈 해결되어 클로징합니다.

감사합니다 👍
