### ISSUE TITLE
1-js/05-data-types/02 Numbers 번역 희망

### ISSUE THREAD

**Issue by rlagksruf16** [javascript-tutorial/ko.javascript.info#92]
우연히 알게되서 들어오게 되었습니다. 
제목과 같은 부분 번역을 희망하는데 이렇게 issue 등록하고 권한 부여받은 spreedsheetd의 translater 부분에 아이디를 입력하면 되는건가요!?

**Comment by Violet-Bora-Lee** [comment]
네 말씀해주신 방법으로 진행하시면 됩니다.
다만 번역하시겠다고 한 article은 이미 번역과 리뷰가 끝난 상태이오니 readme.md파일과 dashboard를 확인부탁드립니다

**Comment by rlagksruf16** [comment]
혹시 한번 확인해주시겠어요? dashboard에는 Numbers 부분이 incomplete 이라고 되어 있네요! 
수고 많으십니다.

**Comment by Violet-Bora-Lee** [comment]
엇 그렇네요! 제가 윗줄이랑 착각했나봐요~
incomplete되어있는건 해주신 것처럼 깃헙 아이지 적어주시고, in progress로 바꿔주신다음 작업하시면 됩니다 :)

**Comment by rlagksruf16** [comment]
감사합니다!!

**Comment by Violet-Bora-Lee** [comment]
장기간 응답이 없으셔서 @Jaehyunleejava 님이 작업 진행해주셨습니다.
https://github.com/javascript-tutorial/ko.javascript.info/pull/357
