### ISSUE TITLE
[대시보드 권한 요청] 

### ISSUE THREAD

**Issue by kellywoo** [javascript-tutorial/ko.javascript.info#934]
## Gmail 아이디
kelly.kh.woo@gmail.com

안녕하세요!
이전에 요청 드렸었는데 아마 권한 부여가 잘 안된 것 같습니다.
그래서 다시 한번 요청 드리겠습니다.
번역하려는 내역은  Selection and Range 입니다.
🙇‍♂️

**Comment by Violet-Bora-Lee** [comment]
안녕하세요
권한 드려서 이슈 종료하겠습니다 😄
