### ISSUE TITLE
[오타수정] iterable 객체 파트 요약 부분

### ISSUE THREAD

**Issue by hspyo** [javascript-tutorial/ko.javascript.info#941]
## 원문
link https://ko.javascript.info/iterable#ref-794
![image](https://user-images.githubusercontent.com/53952734/101273673-ecca2100-37da-11eb-844b-77e542ff596a.png)

## 오타수정
value가 다음 값이 됩니니다. -> value가 다음 값이 됩니다.

## 이슈

명백한 오타가 있어서 수정했습니다 :)

## Pull Request(PR)를 통해 수정할 의향이 있습니까?
네

**Comment by Violet-Bora-Lee** [comment]
이슈 해결되어 클로징 합니다.
감사합니다 👍
