### ISSUE TITLE
[Bug report] 해답 버튼 눌렀는데 열리지가 않습니다

### ISSUE THREAD

**Issue by confidential-nt** [javascript-tutorial/ko.javascript.info#943]
## 🐛 Bug report

과제의 정답을 확인하려고 해답 버튼을 누르면 
Uncaught Error: Cannot find module './ko.yml'
이런 오류가 개발자 콘솔창에 뜨고 해답창은 뜨지 않습니다

## 환경

저는 현재 윈도우10, 구글크롬을 사용하고 있습니다

**Comment by jyh7a** [comment]
저도 같은 문제가 발생하네요... 파일이 사라진듯??

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 해결하는 PR을 engine 저장소에 제출해둔 상태입니다
조금만 대기해주세요

https://github.com/javascript-tutorial/engine/pull/30
