### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by YongPilMoon** [javascript-tutorial/ko.javascript.info#954]
## 모던 JavaScript 튜토리얼을 알게 된 경로
google 검색

## 컨트리뷰팅 가이드를 1회 이상 정독하셨나요?
네. 정독하였습니다.

## Gmail 아이디
m71661@gmail.com

**Comment by Violet-Bora-Lee** [comment]
권한드렸습니다. 감사합니다.
