### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by miraten** [javascript-tutorial/ko.javascript.info#958]
## 모던 JavaScript 튜토리얼을 알게 된 경로
javascript.info 사이트를 보다가, 한글 번역본을 알게 되었고, 여기서 문서를 보다가 번역에 참여할 수 있음을 알게 되었습니다.

## 컨트리뷰팅 가이드를 1회 이상 정독하셨나요?
네. 정독하였습니다.

## Gmail 아이디
emicree@gmail.com

**Comment by Violet-Bora-Lee** [comment]
권한드렸습니다. 감사합니다.
