### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by omg-xodnd** [javascript-tutorial/ko.javascript.info#959]
## 모던 JavaScript 튜토리얼을 알게 된 경로
자바스크립트 학습 자료를 찾다가 알게 되었고, 감사하게도 많은 도움을 받을 수 있었습니다.
지식을 나누는 훌륭한 프로젝트에 참여하여 조금이나마 기여하고 싶습니다.
잘 부탁드립니다!

## 컨트리뷰팅 가이드를 1회 이상 정독하셨나요?
네, 정독하였습니다.

## Gmail 아이디
taew3167@gmail.com

**Comment by Violet-Bora-Lee** [comment]
권한드렸습니다. 감사합니다.
