### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by humblEgo** [javascript-tutorial/ko.javascript.info#968]
## 모던 JavaScript 튜토리얼을 알게 된 경로
팀 프로젝트 중 JavaScript를 학습하다가 팀원이 추천해줘서 알게 되었습니다. 도움 많이 받은 만큼 자잘하게 미번역된 부분 번역하는데 기여하고 싶습니다~!

## 컨트리뷰팅 가이드를 1회 이상 정독하셨나요?
네. 정독하였습니다~!

## Gmail 아이디
injun.woo30000@gmail.com

**Comment by Violet-Bora-Lee** [comment]
안녕하세요 권한 드렸습니다
환영합니다 😄
