### ISSUE TITLE
[오타수정] 재귀와 스택 오타

### ISSUE THREAD

**Issue by Kwakcena** [javascript-tutorial/ko.javascript.info#970]
## 원문
[재귀와 스택](https://ko.javascript.info/recursion#ref-959)
![스크린샷 2021-01-08 오전 2 22 18](https://user-images.githubusercontent.com/45390172/103923350-56ca4300-5158-11eb-9882-e8124dfbe058.png)
## 오타수정
최적화기 -> 최적화가
## 이슈
오타 수정입니다.

## Pull Request(PR)를 통해 수정할 의향이 있습니까?
네

**Comment by Violet-Bora-Lee** [comment]
이슈 해결하여, 본 이슈는 클로징 시키겠습니다. 제보 감사합니다.
