### ISSUE TITLE
[오타수정] 파트1 6.7 단순오타

### ISSUE THREAD

**Issue by humblEgo** [javascript-tutorial/ko.javascript.info#972]
## 원문
Part 1 6.7 'new Function' 문법

![image](https://user-images.githubusercontent.com/54612343/104021664-8170d600-5202-11eb-80af-dbd9f9b07cc5.png)

1. `new Function`를
2. 렉시켤
 
## 오타수정
1. `new Function`을
2. 렉시컬

## 이슈
1.  목적격 조사 '-를'은 앞 음절이 모음으로 끝나는 경우, 목적격 조사 '-을'은 앞 음절이 자음으로 끝나는 경우에 쓰입니다. `new Funciton`은 뉴펑션으로 발음되므로, 이어서 목적격 조사 '-을'이 위치하는 것이 자연스럽습니다. 그리고 해당 문단을 제외하고는 모두 "`new Function`을" 이라고 적혀있습니다. 때문에 오타라 판단했습니다. 
2. 'Lexical'은 문서 전반에 걸쳐 '렉시컬'로 번역되어있으므로, '렉시켤'은 오타라 판단됩니다.

## Pull Request(PR)를 통해 수정할 의향이 있습니까?
넵~!

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 오래 적체된 이슈여서 제가 해결하였습니다.
제보해주셔서 감사합니다 👍
