### ISSUE TITLE
[오번역수정] Part 2 - 2.4 브라우저 기본 동작

### ISSUE THREAD

**Issue by Shubidumdu** [javascript-tutorial/ko.javascript.info#984]
## 오번역
![image](https://user-images.githubusercontent.com/54790378/105707879-f52b1680-5f56-11eb-916b-ad79ea1910c8.png)
해당 본문에서 설명하는 것과 정 반대의 의미로 섹션의 제목이 번역된 것 같습니다.

## 번역

기본 동작을 너무 남용하지 마세요
&#8594; **기본 동작 막기**를 너무 남용하지 마세요.

## 이슈

해당 문서의 앞부분 내용에서 이미 "기본 동작 막기"로 번역이 되었으므로, 이를 그대로 이용해 번역하면 문제 없을 것으로 보입니다.

## Pull Request(PR)를 통해 수정할 의향이 있습니까?
네, 가능합니다.

**Comment by Violet-Bora-Lee** [comment]
이슈 제보해주셔서 감사합니다.
오래 적체되어서 제가 해결하였습니다.
감사합니다 👍
