### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by judoaseeta** [javascript-tutorial/ko.javascript.info#989]
## 모던 JavaScript 튜토리얼을 알게 된 경로
검색하다 번역되지 않은 컨텐츠를 읽었습니다.

## 컨트리뷰팅 가이드를 1회 이상 정독하셨나요?
네 읽었습니다.

## Gmail 아이디
judoaseeta@gmail.com

**Comment by Violet-Bora-Lee** [comment]
수정 권한 드렸습니다
