### ISSUE TITLE
번역 작업을 희망합니다.

### ISSUE THREAD

**Issue by wnsrl56** [javascript-tutorial/ko.javascript.info#99]
안녕하세요. 우연히 리포를 탐험하다 찾게 되었습니다.

새로 자바스크립트를 시작하는 분들께,
조금이나마 도움이 되고자 번역을 희망합니다!

email: wnsrl56@gmail.com

**Comment by Violet-Bora-Lee** [comment]
안녕하세요. 
권한 추가해드렸습니다.
리뷰도 많은 도움이 필요합니다 :)
많은 활동 부탁드려요~
