### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by 0ranzjuice** [javascript-tutorial/ko.javascript.info#994]
## 모던 JavaScript 튜토리얼을 알게 된 경로
ex) 친구가 추천해줘서 알게되었습니다.

## 컨트리뷰팅 가이드를 1회 이상 정독하셨나요?
ex) 네. 정독하였습니다.

## Gmail 아이디
ex) q58dny@gmail.com

**Comment by Violet-Bora-Lee** [comment]
수정 권한 드렸습니다.
