### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by jan166** [javascript-tutorial/ko.javascript.info#995]
## 모던 JavaScript 튜토리얼을 알게 된 경로
친구와 함께 컨트리뷰트 하고자 합니다!

## 컨트리뷰팅 가이드를 1회 이상 정독하셨나요?
네. 정독하였습니다.

## Gmail 아이디
janettt16@gmail.com

**Comment by Violet-Bora-Lee** [comment]
수정 권한 드렸습니다.
