### ISSUE TITLE
[대시보드 수정 권한 요청] 

### ISSUE THREAD

**Issue by kei9641** [javascript-tutorial/ko.javascript.info#997]
## 모던 JavaScript 튜토리얼을 알게 된 경로
SOS Masters를 통해 알게 되었습니다.

## 컨트리뷰팅 가이드를 1회 이상 정독하셨나요?
네. 정독하였습니다.

## Gmail 아이디
dudwn3036@naver.com

**Comment by Violet-Bora-Lee** [comment]
수정 권한 드렸습니다
